### ISSUE TITLE
"Model_Invalid" raised when the model validator detects a duplicate variable in the same constraint

### ISSUE THREAD

**Issue by PepSalehi** [google/or-tools#3614] opened 2023-01-03 19:30 UTC
**What version of OR-Tools and what language are you using?**
Version: 9.5.2237
Language: Python 3.8.11 

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP
**What operating system (Linux, Windows, ...) and version?**
Windows
**What did you do?**
This is a simplified example. It shows that "FindDuplicateVarIndex" in model_validator.cc causes model to be "invalid" and not solved, which it probably shouldn't and we can solve it in Julia/JuMP. 

I don't know how to explain the issue other than by an example. Assume there are "m" products, comprised of "f" features each. features 1 and 2 are also available as a bundled option. The objective is to minimize the number of features used (with some additional constraints, skipped for now). 
The core issue is this constraint, which specifies that a feature is either offered alone, or as part of a bundle, but not both:
$v_{ij} = y_i +  q_{ib}y_b \quad \forall j\in J $
where $q$ is the feature-bundle incidence matrix (1 if a feature is part of the bundle, zero otherwise), and $v_{ij}$ is whether feature $i$ exists in product $j$. 
The problem is that when $q=0$ for a given $i,j$, then or-tools replaces $y_i$ with $v_{ij}$. and then complains about duplicate constraints:
` C02: +1 v_(2,_0) -1 v_(2,_0)  = 0`
and 
`"'In constraint #2: var_index #11 appears several times. Constraint proto: lower_bound: 0 upper_bound: 0 var_index: 11 var_index: 11 coefficient: 1 coefficient: -1'"`

The code to reproduce the error: 

```python
import pathlib
import numpy as np
import pandas as pd
import pickle
from ortools.linear_solver import pywraplp
# from ortools.model_builder.python import model_builder
from ortools.linear_solver.python import model_builder


```

* 3 products
* 5 features 
* 1 bundle, comprising features 1 and 2 

```python
total_number_of_choices = 5 + 1
```

```python
total_unique_products = 3
```

```python
standalone_features = list(range(5))
```

```python
total_sold = 4
```

```python
feature_bundle_incidence_matrix = {}
```

```python
for idx, feature in enumerate(standalone_features):
    feature_bundle_incidence_matrix[idx,0] = 0
    
feature_bundle_incidence_matrix[0,0] = 1
feature_bundle_incidence_matrix[1,0] = 1 
```

```python
target_volume = 0.7
bundle_start_idx = len(standalone_features)
T = minimum_to_be_covered = 0.8 * len(standalone_features)
```

```python
# Model
model = model_builder.ModelBuilder()
y = {}
m = {}
v = {}
for i in range(total_number_of_choices):
    y[i] = model.new_bool_var(f"y_{i}")
for j in range(total_unique_products):
    m[j] = model.new_bool_var(f"m_{j}")
for j in range(total_unique_products):
    for i in range(len(standalone_feature)):
        v[i, j] = model.new_bool_var(f"v_{(i,j)}")
```

```python
for j in range(total_unique_products):
    for i in range(len(standalone_features)):
        model.add(
            v[i, j]
            == (
                y[i]
                + 
                (feature_bundle_incidence_matrix[(i , 0)] * y[bundle_start_idx])   
            )
        )
```

```python
feature_bundle_incidence_matrix
```

    {(0, 0): 1, (1, 0): 1, (2, 0): 0, (3, 0): 0, (4, 0): 0}

```python
model.add(
        model_builder.LinearExpr.sum(
            [m[j]  for j in range(total_unique_products)]
        )
        >= target_volume * total_sold
    )

for j in range(total_unique_products):
    model.add(
        (
            model_builder.LinearExpr.sum(
                [
                    v[i, j] 
                    for i in range(len(standalone_features))
                   
                ]
            )
            - (minimum_to_be_covered * m[j])
        )
        >= 0
    )


```

```python
obj = model_builder.LinearExpr.sum([y[i] for i in range(total_number_of_choices)])
model.minimize(obj)
```

```python
solver = model_builder.ModelSolver("SCIP")
```

```python
status = solver.solve(model)
```

```python
status 
```

    <SolveStatus.MODEL_INVALID: 9>

```python
solver.status_string
```

    'In constraint #2: var_index #11 appears several times. Constraint proto: lower_bound: 0 upper_bound: 0 var_index: 11 var_index: 11 coefficient: 1 coefficient: -1'

```python
s = model.export_to_lp_string()
with open('min_example_log.txt', 'w') as f:
    f.writelines(s) 
```

```python
import ortools 
ortools.__version__
```

    '9.5.2237'

```python

```

**What did you expect to see**
obj_value =3. 
Here is the Julia/JuMP code to solve it 

```julia
using DataFrames 
using JLD2
using Pipe: @pipe
using JuMP, CPLEX, Test 
using Plots
using DataStructures
```

```julia
total_number_of_choices = 5 + 1
total_unique_products = 3
```

    3

```julia
standalone_features = [1,2,3,4,5];
total_sold = 4;
```

```julia
target_coverage = 0.7
bundle_start_idx = length(standalone_features)+1
T = minimum_to_be_covered = 0.8 * length(standalone_features)
```

    4.0

```julia

```

```julia
feature_bundle_incidence_matrix = Dict()
for (idx, feature) in enumerate(standalone_features)
    feature_bundle_incidence_matrix[idx,1] = 0
end
    
feature_bundle_incidence_matrix[1,1] = 1
feature_bundle_incidence_matrix[2,1] = 1 
```

    1

```julia
model = Model(CPLEX.Optimizer; bridge_constraints = true)
# set_optimizer_attribute(model, "CPX_PARAM_EPINT", 1e-8);
@variable(model, y[1:total_number_of_choices], Bin);
@variable(model, m[1:total_unique_products], Bin);

v= Dict()
for j in  range(1, stop=total_unique_products)
    for i in range(1, stop=length(standalone_features))
        v[i,j] = @variable(model, binary = true) #  @variable(model, v[i,j], Bin);
    end
end 
```

```julia
feature_bundle_incidence_matrix
```

    Dict{Any, Any} with 5 entries:
      (3, 1) => 0
      (1, 1) => 1
      (5, 1) => 0
      (4, 1) => 0
      (2, 1) => 1

```julia
for j in range(1, stop=total_unique_products)
    for i in range(1, stop=length(standalone_features))
           @constraint(model,v[i, j] == (y[i] + 
                 feature_bundle_incidence_matrix[(i , 1)] * y[bundle_start_idx]
            ))
     end         
end 
```

```julia
# volume constraint 
@constraint(model,
        sum(
            [m[j]  for j in  range(1, stop=total_unique_products)]
        )
        >= target_coverage * total_sold
    );


```

```julia
# configuration coverage constraint 
for j in range(1, stop=total_unique_products)
       @constraint(model,
           (
                sum(
                    [v[i, j] for i in  range(1, stop=length(standalone_features))  ]
                ) -  minimum_to_be_covered * (m[j])   
            )
            >= 0
        )
end 
```

```julia
@objective(
    model,
    Min,
    sum([y[i] for i in range(1, stop=total_number_of_choices)]));
```

```julia
optimize!(model)

```

    Version identifier: 12.10.0.0 | 2019-11-26 | 843d4de2ae
    Tried aggregator 2 times.
    MIP Presolve eliminated 1 rows and 5 columns.
    Aggregator did 9 substitutions.
    Reduced MIP has 9 rows, 10 columns, and 27 nonzeros.
    Reduced MIP has 9 binaries, 1 generals, 0 SOSs, and 0 indicators.
    Presolve time = 0.00 sec. (0.04 ticks)
    Found incumbent of value 5.000000 after 0.00 sec. (0.05 ticks)
    Probing time = 0.00 sec. (0.01 ticks)
    Tried aggregator 1 time.
    MIP Presolve eliminated 6 rows and 4 columns.
    Reduced MIP has 3 rows, 6 columns, and 9 nonzeros.
    Reduced MIP has 5 binaries, 1 generals, 0 SOSs, and 0 indicators.
    Presolve time = 0.00 sec. (0.01 ticks)
    Probing time = 0.00 sec. (0.00 ticks)
    Tried aggregator 1 time.
    Detecting symmetries...
    Reduced MIP has 3 rows, 6 columns, and 9 nonzeros.
    Reduced MIP has 5 binaries, 1 generals, 0 SOSs, and 0 indicators.
    Presolve time = 0.00 sec. (0.01 ticks)
    Probing time = 0.00 sec. (0.00 ticks)
    Clique table members: 5.
    MIP emphasis: balance optimality and feasibility.
    MIP search method: dynamic search.
    Parallel mode: deterministic, using up to 12 threads.
    Root relaxation solution time = 0.00 sec. (0.00 ticks)
    
            Nodes                                         Cuts/
       Node  Left     Objective  IInf  Best Integer    Best Bound    ItCnt     Gap
    
    *     0+    0                            5.0000        2.0000            60.00%
    *     0+    0                            3.0000        2.0000            33.33%
          0     0        cutoff              3.0000        3.0000        2    0.00%
          0     0        cutoff              3.0000        3.0000        2    0.00%
    Elapsed time = 0.02 sec. (0.11 ticks, tree = 0.01 MB, solutions = 2)
    
    Root node processing (before b&c):
      Real time             =    0.02 sec. (0.11 ticks)
    Parallel b&c, 12 threads:
      Real time             =    0.00 sec. (0.00 ticks)
      Sync time (average)   =    0.00 sec.
      Wait time (average)   =    0.00 sec.
                              ------------
    Total (root+branch&cut) =    0.02 sec. (0.11 ticks)
    

```julia
objective_value(model)
```

    3.0

```julia
for variable in all_variables(model)
    if (value(variable)) > 0
        println("$(name(variable)) = $(value(variable))")
    end
end
```

    y[3] = 1.0
    y[4] = 1.0
    y[6] = 1.0
    m[1] = 1.0
    m[2] = 1.0
    m[3] = 1.0
 

```julia
write_to_file(model, "min_example_julia.lp")
```

**What did you see instead?**

"'In constraint #2: var_index #11 appears several times. Constraint proto: lower_bound: 0 upper_bound: 0 var_index: 11 var_index: 11 coefficient: 1 coefficient: -1'"
The problem is that or-tools replaces a binary variable with its equivalent variable (when applicable), but then complains and aborts the problem as a results. e.g., 
 C02: +1 v_(2,_0) -1 v_(2,_0)  = 0
while the julia model is (julia is indexed at one)
c3: -1 y_3_ + 1 x12 = 0

**Anything else we should know about your project / environment**

**Comment by lperron** [comment] 2023-01-04 05:56
the problem is not duplicate constraint, it is duplicate variables in a constraint.

**Comment by lperron** [comment] 2023-01-04 06:09
Can you try disabling import of both pywraplp and model_builder ?

**Comment by lperron** [comment] 2023-01-04 07:19
I pushed the fix + unit tests.

Many thanks for the bug report.

**Closed** 2023-01-04 07:19 UTC

**Comment by PepSalehi** [comment] 2023-01-04 15:05
Thanks for the quick fix. Thank you to you and the team for all you do.
