### ISSUE TITLE
Windows Make: wrong SHELL used (zlib.h cannot be copied)

### ISSUE THREAD

**Issue by bacalfa** [google/or-tools#576] opened 2018-02-09 16:07 UTC
I can't understand why the following happens:

```
C:\Users\abreucb\Downloads\or-tools>tools\make third_party
ERROR: Invalid pattern is specified in "path:pattern".
which: fsc: unknown command
tools\mkdir.exe -p dependencies\install\bin
tools\mkdir.exe -p dependencies\install\lib
tools\mkdir.exe -p dependencies\install\include\coin
copy dependencies\sources\zlib-1.2.11\zlib.h dependencies\install\include
process_begin: CreateProcess((null), copy dependencies\sources\zlib-1.2.11\zlib.
h dependencies\install\include, ...) failed.
make (e=2): The system cannot find the file specified.
tools\make: *** [dependencies\install\include\zlib.h] Error 2
```

when I can manually execute the `copy` command without errors:

```
C:\Users\abreucb\Downloads\or-tools>copy dependencies\sources\zlib-1.2.11\zlib.h
 dependencies\install\include
        1 file(s) copied.
```

Does not having admin rights have something to do with this?

**Comment by bacalfa** [comment] 2018-02-21 12:55
I temporarily obtained admin rights, and the error continues.

![image](https://user-images.githubusercontent.com/1297074/36481044-8a4927c8-16dc-11e8-89dc-ffcbaf55b9d8.png)

I still haven't been able to build ortools on Windows. :(

**Comment by Mizux** [comment] 2018-02-21 13:33
Hi,

I'm on it,

Otherwise you could try the CMake install https://github.com/google/or-tools/tree/master/cmake
there is also an appveyor.yml script which test the cmake stuff on windows...
https://github.com/google/or-tools/blob/master/appveyor.yml

log here: https://ci.appveyor.com/project/Mizux/cmake-ortools/build/3/job/6a0ucut27c285q9o

**Comment by Mizux** [comment] 2018-02-21 13:56
I think patch for #593 should fix the `ERROR: Invalid pattern`

Now i'll continue to check that zlib is correctly downloaded and extracted on windows...

**Comment by bacalfa** [comment] 2018-02-21 14:10
Thanks a lot for looking into this! I'm trying the CMake way now, but I'm getting an error saying it could not find an instance of Visual Studio. So annoying. Working on it.

**Comment by Mizux** [comment] 2018-02-23 13:23
I'm closing this issue, feel free to open a new one for CMake related bugs !

I will also soon merge mizux/dev which contains few Makefile fixes...

**Comment by Mizux** [comment] 2018-02-28 09:46
Hi,
Be able to reproduce the issue on appveyor CI
https://ci.appveyor.com/project/Mizux/or-tools/build/6/job/et8jara0cpe6mo8s#L140

As far as I know, it seems the appveyor prompt (i.e and yours ?) and the one use on my windows VM doesn't escape special character the same way.
Thus I add to patch Makefile(s) to first deal with quotes space etc. (cf mizux/dev branch)

**Comment by Mizux** [comment] 2018-02-28 12:47
Find a way to reproduce !
This is due to the shell version used...
On AppVeyor they use `C:\Program Files\Git\bin\sh.exe`

i.e.
```sh
$ set "PATH=C:\Program Files\Git\bin;%PATH%"
$ where sh.exe
C:\Program Files\Git\bin\sh.exe
$ make detect
...
SHELL = C:\Program Files\Git\bin\sh.exe
```
and you'll get lots of errors...

Expected behaviour:
```sh
$ where sh.exe
INFO: Could not find files for the given pattern(s).
$ make detect
...
SHELL = sh.exe
...
```

and everything is fine, which is odd since SHELL is technically "not found"...

Investigating....

**Comment by bacalfa** [comment] 2018-02-28 14:37
Thanks for looking into this. Let me know when I can test on my end.

**Comment by Mizux** [comment] 2018-02-28 16:35
Hi,
After many tests I would say the only way to have something working is to **NOT** have `sh.exe` in your `PATH` (i.e. `where sh` must fail)

I tried to set SHELL=cmd / cmd.exe / C:\Windows\System32\cmd.exe (FYI everything have the same behaviour) inside `Makefile`, `makefile\Makefile.port.mk`, makefile\Makefile.win.mk` or using `set SHELL=cmd` in the prompt... without any success (-_-;)

Note: `make detect` will change according to where SHELL is placed
*BUT* only if Make doesn't found sh.exe otherwise it seems Make simply ignore the variable (wherever you place it) and still use sh.exe -> `copy` not working, sed wrong pattern etc...

SO the only solution I see:
OR-Tools: use `$(error` if sh.exe is in the path and stop...
For you: try to hack your path to "remove" sh.exe or (rm/rename the file)
-> I'll test this hack on appveyor to see if doable

Sorry for the inconvenience, any solution/PR is welcome...

src: https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html#Choosing-the-Shell
ps: I'll close this issue once I have a workaround on appveyor...

**Comment by bacalfa** [comment] 2018-02-28 21:53
OK, I'll see if I try it tomorrow. Unfortunately, building software on Windows can be a tremendous pain, while on UNIX it's a breeze 99% of the time.

**Comment by bacalfa** [comment] 2018-03-01 13:52
Quick update. I was able to get past that copy error following your suggestions! The culprit was sh.exe in C:\msys\1.0\bin. I had to temporarily remove it from %PATH% by running the following [command](https://stackoverflow.com/a/39141462/2359430) (because I currently don't have admin rights):

`set PATH=%PATH:C:\msys\1.0\bin;=%`

Then many steps later I had an issue with downloading swigwin, but it seems it's because SourceForge is currently down (the link http://prdownloads.sourceforge.net/swig/swigwin-3.0.12.zip doesn't work). Will retry later.

**Comment by Mizux** [comment] 2018-03-01 14:14
Yup all my jobs are down:
https://ci.appveyor.com/project/Mizux/or-tools/build/job/wkdybybeugg3aouy

Please also notice some issue with python include path on my branch currently trying to fix them...

**Comment by bacalfa** [comment] 2018-03-01 18:08
The download link works now and I was finally able to run `tools\make third_party` to completion for the first time! I'm currently running `tools\make cc python pypi_archive` with a CPLEX variable defined in Makefile.local. We'll see what happens.

**Comment by bacalfa** [comment] 2018-03-01 19:36
It seemed to work, but it didn't read the Makefile.local file from the root directory. How do I ensure external solvers are considered when building ortools doing `tools\make`?

Also, the last part of the log is the following:

```
del temp-python36\ortools\setup.py-e
Could Not Find C:\Users\abreucb\Downloads\or-tools\temp-python36\ortools\setup.py-e
```

That file doesn't really exist.

**Comment by bacalfa** [comment] 2018-03-01 21:36
I'm getting linking errors (unresolved symbol). This is the last call before the errors appear:

```
cl /EHsc /MD /nologo /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS -nologo  /O2 -D
NDEBUG /I. /Iortools\\gen /IC:\\Users\\abreucb\\Downloads\\or-tools\\dependencie
s\\install\\include /DGFLAGS_DLL_DECL= /DGFLAGS_DLL_DECLARE_FLAG= /DGFLAGS_DLL_D
EFINE_FLAG= /IC:\\Users\\abreucb\\Downloads\\or-tools\\dependencies\\install\\in
clude  /IC:\\Users\\abreucb\\Downloads\\or-tools\\dependencies\\install\\include
 /I\\include /DGOOGLE_GLOG_DLL_DECL= /IC:\\Users\\abreucb\\Downloads\\or-tools\\
dependencies\\install\\include /IC:\\Users\\abreucb\\Downloads\\or-tools\\depend
encies\\install\\include\\coin /DUSE_CBC /IC:\\Users\\abreucb\\Downloads\\or-too
ls\\dependencies\\install\\include /IC:\\Users\\abreucb\\Downloads\\or-tools\\de
pendencies\\install\\include\\coin /DUSE_CLP   /I'C:\Program Files\IBM\ILOG\CPLE
X_Studio1271\cplex'\\include /DUSE_CPLEX  /DUSE_GLOP /DUSE_BOP /D__WIN32__ /DPSA
PI_VERSION=1 objs/cvrp_disjoint_tw.obj lib\\ortools.lib lib\\cvrptw_lib.lib lib\
\ortools.lib C:\\Users\\abreucb\\Downloads\\or-tools\\dependencies\\install\\lib
\\zlib.lib psapi.lib ws2_32.lib shlwapi.lib /Febin\\cvrp_disjoint_tw.exe
```

I believe the CPLEX .lib file (in my case, cplex1271.lib) is missing from the command above. That .lib file doesn't appear in the call if I include `$(STATIC_CPLEX_LNK)` in the definition of `DEPENDENCIES_LNK`, but it does appear if I include it in the definition of `OR_TOOLS_LD_FLAGS`. This doesn't seem intuitive to me, because the .lib file for all other solvers like Gurobi, SCIP, etc. are defined in the former variable. In other words, I have the following on my Makefile.win.mk:

`OR_TOOLS_LD_FLAGS = $(ZLIB_LNK) $(SYS_LNK) $(STATIC_CPLEX_LNK)`

OK, so the C++ build finished. Now I'm having issues with the Python build. First, it didn't like the include of CPLEX's include folder:

```
cl : Command line warning D9024 : unrecognized source file type 'Files\IBM\ILOG\
CPLEX_Studio1271\cplex'\\include', object file assumed
cl : Command line warning D9027 : source file 'Files\IBM\ILOG\CPLEX_Studio1271\c
plex'\\include' ignored
```

Then, I got a bunch of unresolved symbol errors. Probably due to not listing the CPLEX .lib file. Will investigate it tomorrow.

**Comment by Mizux** [comment] 2018-03-01 22:15
Hi,

Thanks for your time, and sorry that windows support is still a little bit a mess.
To be honest, I still not play with the optional third parties, I'll test it tomorrow too !

I'll try to upgrade the `make detect` to get info on C++ flags use during compilation (add a detect_cc target)...

For Python since we have SWIG wrapper library, I would say it doesn't take into account optional third parties, I'll check tomorrow...

**Comment by bacalfa** [comment] 2018-03-02 16:53
Thanks! Now I only have the unresolved symbol error when building Python.

```
C:\Users\abreucb\Downloads\or-tools>tools\make cc python pypi_archive
process_begin: CreateProcess((null), which fsc, ...) failed.
tools\make: Nothing to be done for `cc'.
copy dependencies\\install\\bin\\protoc.exe dependencies\\sources\\protobuf-3.5.
1\\src
        1 file(s) copied.
cd dependencies\\sources\\protobuf-3.5.1\\python && "C:/Users/abreucb/AppData/Lo
cal/Continuum/anaconda3\\python.exe" setup.py build
running build
running build_py
link /DLL /LTCG /debug /OUT:lib\\_pywrapcp.dll objs\\swig\\constraint_solver_pyt
hon_wrap.obj lib\\ortools.lib psapi.lib ws2_32.lib shlwapi.lib "C:/Users/abreucb
/AppData/Local/Continuum/anaconda3\\libs\\python36.lib"
Microsoft (R) Incremental Linker Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library lib\\_pywrapcp.lib and object lib\\_pywrapcp.exp
ortools.lib(cplex_interface.obj) : error LNK2001: unresolved external symbol __i
mp_CPXLaddcols
...
lib\\_pywrapcp.dll : fatal error LNK1120: 40 unresolved externals
tools\make: *** [lib/_pywrapcp.dll] Error 1120
```

**Comment by Mizux** [comment] 2018-03-02 17:35
Sorry in the train on smartphone
My guess: python Wrapper are linked to ORTOOLS_LNK -> could you try to print its value in detect python at bottom of the file and verify that cplex is present or maybe in python_lnk
https://github.com/google/or-tools/blob/master/makefiles/Makefile.python.mk#L228 hope it will help you

**Comment by bacalfa** [comment] 2018-03-02 18:10
I changed the bottom of file makefiles\Makefile.python.mk as follows:

```
detect_python:
	@echo PYTHON_VERSION = $(PYTHON_VERSION)
	@echo PYTHON3 = $(PYTHON3)
	@echo PYTHON_EXECUTABLE = $(PYTHON_EXECUTABLE)
	@echo PYTHON_INC = $(PYTHON_INC)
	@echo PYTHON_LNK = $(PYTHON_LNK)
	@echo SWIG_PYTHON3_FLAG = $(SWIG_PYTHON3_FLAG)
    @echo ORTOOLS_LNK = $(ORTOOLS_LNK)
ifeq ($(SYSTEM),unix)
	@echo SET_PYTHONPATH = $(SET_PYTHONPATH)
endif
```

But when I run `tools\make detect_python` I only get:

```
C:\Users\abreucb\Downloads\or-tools>tools\make detect_python
process_begin: CreateProcess((null), which fsc, ...) failed.
PYTHON_VERSION = 36
PYTHON3 = true
PYTHON_EXECUTABLE = "C:/Users/abreucb/AppData/Local/Continuum/anaconda3\\python.
exe"
PYTHON_INC = /I"C:/Users/abreucb/AppData/Local/Continuum/anaconda3\\include"
PYTHON_LNK = "C:/Users/abreucb/AppData/Local/Continuum/anaconda3\\libs\\python36
.lib"
SWIG_PYTHON3_FLAG = -py3 -DPY3
```

???

**Comment by bacalfa** [comment] 2018-03-02 18:13
I modified the bottom of makefiles\Makefile.python.mk as you suggested, and that variable is empty:

```
C:\Users\abreucb\Downloads\or-tools>tools\make detect_python
process_begin: CreateProcess((null), which fsc, ...) failed.
PYTHON_VERSION = 36
PYTHON3 = true
PYTHON_EXECUTABLE = "C:/Users/abreucb/AppData/Local/Continuum/anaconda3\\python.
exe"
PYTHON_INC = /I"C:/Users/abreucb/AppData/Local/Continuum/anaconda3\\include"
PYTHON_LNK = "C:/Users/abreucb/AppData/Local/Continuum/anaconda3\\libs\\python36
.lib"
SWIG_PYTHON3_FLAG = -py3 -DPY3
ORTOOLS_LNK =
```

**Comment by lperron** [comment] 2018-03-02 21:08
the link command is missing the path to the cplex dll.

**Comment by bacalfa** [comment] 2018-03-02 21:30
Yes, but what do I have to do? Should I set any other variable?

**Closed** 2018-03-05 10:16 UTC
Labels: Windows, bug, help wanted
