### ISSUE TITLE
Segmentation Fault when setting cp_model_presolve = False

### ISSUE THREAD

**Issue by timothylowjc** [google/or-tools#1861] opened 2020-01-29 09:37 UTC
**What version of OR-tools and what language are you using?**
Version: master
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows Subsystem Linux (Ubuntu 18.04)

**What did you do?**
Wrote a solver that works fine, but have been attempting to change solver.parameters to increase solving speed. When solver.parameters.cp_model_presolve = False, this results in a Segmentation Fault. 

The error message is quite literally "Segmentation fault (core dumped)".

[cpmodelproto.txt](https://github.com/google/or-tools/files/4127182/cpmodelproto.txt)

Model Proto is as above. 

I understand from searching that the Segmentation Fault sometimes occurs during routing problems, but can't quite find anything about it while using it for CP-SAT, so figured I'd open a bug report. If I've made an error here, do let me know and I'll delete this post!

**Comment by lalithsuresh** [comment] 2020-01-31 21:03
I've seen this happen when switching off presolve in the CP-SAT solver on Java as well.

**Comment by lperron** [comment] 2020-02-04 10:33
This seems to be fixed on master. Solving without presolve is very slow.
Solving is done in C++, so the user's language does not impact anything.

**Comment by lperron** [comment] 2020-02-04 10:35
Actually, I can reproduce the crash.

**Comment by lperron** [comment] 2020-02-04 13:08
Thanks again. 

I pushed the fix on master.

**Closed by lperron** 2020-02-04 13:08 UTC
Labels: Bug, Lang: Python, OS: Linux, Solver: CP / CP-SAT Solver

**Comment by timothylowjc** [comment] 2020-02-05 04:01
Sweet! Thanks @lperron for all your work
