### ISSUE TITLE
Python CBC MIP - is there a way to set GAP limit parameter

### ISSUE THREAD

**Issue by praveenxrao** [google/or-tools#694] opened 2018-05-17 14:26 UTC
Hello,

I am trying to set the GAP limit parameter using CBC solver. I can set the Time Limit parameter using:
solver = pywraplp.Solver('Solver',
        pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)
solver.SetTimeLimit(4000) ## set to 4 seconds

Instead of using TimeLimit, can I set a GAP limit?

Thanks

**Comment by Mizux** [comment] 2018-05-18 13:31
Seems now a duplicate of #644

**Closed** 2018-05-18 13:31 UTC
Labels: Duplicate, Help Needed, Python
