### ISSUE TITLE
Pickup and delivery: group nodes pickup nodes by vehicles

### ISSUE THREAD

**Issue by abduakhatov** [google/or-tools#979] opened 2018-12-18 11:26 UTC
I integrated PDP in VRP with Time and Capacity constraints (also Pickup and Delivery). It is working as expected, but there is another feature to implement. Is it possible to assign specific pickup or delivery node to specific car (group nodes to specific). I used following https://github.com/google/or-tools/issues/703

```
routing.AddPickupAndDelivery(1, 2)
routing.solver().Add(routing.VehicleVar(1) == routing.VehicleVar(2))
```

Another question which may possibly be linked to the first one: 
How to tell optimizer that the pickup node is visited (This is used for the purpose, if node is visited, so picked up and needs to be delivered)

**Comment by Mizux** [comment] 2018-12-18 12:02
First you should use `ActiveVar()` sine node may be added one by one it avoi to have the solver hang because one node is added to a route and note the other.

You can get the VehicleVar using the start node of a vehicle.
```python
one = routing.NodeToIndex(1)
two = routing.NodeToIndex(2)
constraintActive = routing.ActiveVar(one) * routing.ActiveVar(two)
# force same vehicle
routing.solver().Add(
  constraintActive * routing.VehicleVar(one) == 
  constraintActive * routing.VehicleVar(two)
# force vehicle N
routing.solver().Add(
  constraintActive * routing.VehicleVar(one) == 
  constraintActive * routing.VehicleVar(routing.Start(N))
```

duplicate of #847

**Comment by abduakhatov** [comment] 2018-12-18 14:52
@Mizux Thank you for answer!
Got another small question. In the code above you a part which adds precedence to visit node one before node two. I have Time constraint added as seperate dimension which is derived from [vrptw](https://developers.google.com/optimization/routing/cvrptw). should i still add the precedence constraint you added?

**Comment by Mizux** [comment] 2018-12-18 15:04
if your time windows does not overlap and `TW.end(pickup) < TW.start(deliver)` then you may remove the precedence constraint since it is just a redundant constraint but if i were you I would keep it just in case.

**Closed** 2018-12-18 15:07 UTC
Labels: Duplicate, Help Needed, Lang: Python

**Comment by abduakhatov** [comment] 2018-12-18 15:10
```
# force vehicle N
routing.solver().Add(
  constraintActive * routing.VehicleVar(one) == 
  constraintActive * routing.VehicleVar(routing.Start(N))
```
In above, I just recently found out that another option would be to create , to say, two lists of nodes for two vehicles relatively. Then setting Disjoint constraints for two lists elements not to be on the same vehicle

**Comment by Mizux** [comment] 2018-12-18 15:18
@abduakhatov yes, it should works
