### ISSUE TITLE
Python installation issue on Apple M1

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [google/or-tools#3009] opened 2021-12-10 11:55 UTC
**What version of OR-Tools and what language are you using?**
Version: master
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Cbc

**What operating system (Linux, Windows, ...) and version?**
MacOSx, M1 chipset

**What did you do?**
1. install ortools via pip
2. try also from downloaded wheel

**What did you expect to see**
Install the latest version (or any version)

**What did you see instead?**

```
$ pip3.8 install ortools                                                                                
ERROR: Could not find a version that satisfies the requirement ortools (from versions: none)
ERROR: No matching distribution found for ortools
$ pip3.8 install ~/Downloads/ortools-9.1.9552-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
ERROR: ortools-9.1.9552-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl is not a supported wheel on this platform.
```

**Anything else we should know about your project / environment**
$ pip3.8 -V                                                                                             
pip 21.3.1 from /Users/andreacassioli/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pip (python 3.8)
$ python3.8 -V                                                                                          
Python 3.8.12
$ uname
Darwin

**Comment by Mizux** [comment] 2021-12-10 12:50
Duplicate of #2722 and #2332

**Closed by Mizux** 2021-12-10 12:50 UTC
Labels: Feature Request, OS: Mac, Cross Compilation
