### ISSUE TITLE
Segmentation fault in CP-SAT

### ISSUE THREAD

**Issue by rybickibartek** [google/or-tools#2591] opened 2021-06-09 10:33 UTC
**What version of OR-Tools and what language are you using?**
Version: v9.0.9048
Language: Python 3.7.5

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Amazon Linux (ami-096f43ef67d75e998) and macOS Catalina 10.15.6 [problem appear on both]

**What did you do?**
I use cp-sat as a subroutine in my algorithm. It is invoked many times [each time with different parameters but structure of a model is the same] and very rarely it ends with segmentation fault, I saved model proto just before - i hope it will be helpful.
[model.txt](https://github.com/google/or-tools/files/6622997/model.txt)

**What did you expect to see**
No segmentation fault

**What did you see instead?**
The following stack trace:
```
Fatal Python error: Segmentation fault

Thread 0x00007f2d5236f700 (most recent call first):

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/threading.py", line 300 in wait

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/threading.py", line 552 in wait

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/site-packages/tqdm/_monitor.py", line 69 in run

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/threading.py", line 926 in _bootstrap_inner

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/threading.py", line 890 in _bootstrap


 

Thread 0x00007f2d715596c0 (most recent call first):

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/site-packages/ortools/sat/pywrapsat.py", line 150 in Solve

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/site-packages/ortools/sat/python/cp_model.py", line 1815 in Solve

  File "/home/ec2-user/local_search/validate_lofs.py", line 165 in create_valid_lofs

  File "/home/ec2-user/local_search/validate_lofs.py", line 200 in add_block

  File "/home/ec2-user/local_search/next_candidate_generator.py", line 122 in _add_blocks

  File "/home/ec2-user/local_search/next_candidate_generator.py", line 179 in get_new_candidate

  File "/home/ec2-user/local_search/simulated_annealing.py", line 23 in simulated_annealing

  File "/home/ec2-user/local_search/simulated_annealing.py", line 76 in run_algorithm

  File "optimize_parameters.py", line 109 in objective

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/site-packages/hyperopt/base.py", line 907 in evaluate

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/site-packages/hyperopt/fmin.py", line 170 in serial_evaluate

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/site-packages/hyperopt/fmin.py", line 292 in run

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/site-packages/hyperopt/fmin.py", line 356 in exhaust

  File "/home/ec2-user/miniconda3/envs/scotch/lib/python3.7/site-packages/hyperopt/fmin.py", line 553 in fmin

  File "optimize_parameters.py", line 178 in <module>

Segmentation fault
```

**Comment by lperron** [comment] 2021-06-09 10:49
I cannot reproduce it.
Do you use special parameters ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 9 juin 2021 à 12:33, rybickibartek ***@***.***> a
écrit :

**Comment by rybickibartek** [comment] 2021-06-09 10:55
This a set of parameters which I use.
```
solver = cp_model.CpSolver()
solver.parameters.num_search_workers = multiprocessing.cpu_count()
solver.parameters.max_time_in_seconds = 10
```

**Comment by lperron** [comment] 2021-06-09 11:04
I ran it ~50 times on master without a crash.
I suppose it is fixed.

I will close the issue. Thanks for the report.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 9 juin 2021 à 12:56, rybickibartek ***@***.***> a
écrit :

**Closed** 2021-06-09 11:04 UTC
Labels: Solver: CP / CP-SAT Solver

**Comment by rybickibartek** [comment] 2021-06-09 11:40
As i wrote before I run it many times in my algorithm. Segmentation fault appears once after 7k steps other times after 14k steps. [in each step structure of a model is the same]. In think that 50 executions is not enough to detect a problem [assuming that it exists].

**Comment by rybickibartek** [comment] 2021-06-10 10:44
I compile stable version from github and run model proto with "examples/cpp/sat_runner.cc" 20k times and described problem didn't occur.

I choose version 8.0.8283 of ortools and run all algorithm [with CP as subroutine] and problem do not occur. I do not know how to explain all of this but i have impression that something is not ok with version 9.0.9048 [or problem is on my side but stack trace suggest that it is not]

**Comment by lperron** [comment] 2021-06-10 11:06
Stable or master? Stable is 9.0.

Le jeu. 10 juin 2021 à 12:44, rybickibartek ***@***.***> a
écrit :

**Comment by rybickibartek** [comment] 2021-06-10 12:56
Stable, I use the following command to clone repo.
```git clone https://github.com/google/or-tools```

**Comment by lperron** [comment] 2021-06-10 14:17
As I said, stable is 9.0.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 10 juin 2021 à 14:56, rybickibartek ***@***.***> a
écrit :
