### ISSUE TITLE
Get Transit value from the solution

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#825] opened 2018-08-21 13:49 UTC
Hello,
Getting the Load works w/o issues.
Trying to get the Demand (Transit) similarly to Load (Cumul) **crashes the program.**

First:
IntVar local_load = model.CumulVar(order, "capacity");
IntVar local_demand = model.TransitVar(order, "capacity");

Then, after solving:
A = solution.Value(local_load).ToString();
B = solution.Value(local_demand).ToString();

Any tips?

**Comment by Mizux** [comment] 2018-09-05 08:39
Maybe, you need to add the TransitVar to the solution
```python
for idx, _ in enumerate(locations):
  routing.AddToAssignment(capacity_dimension.TransitVar(routing.NodeToIndex(idx)))
```

related to #708 (same kind of issue but for looking at SlackVar)

**Comment by Mizux** [comment] 2018-09-05 09:52
Duplicate of #145 cf https://github.com/google/or-tools/issues/145#issuecomment-173176505

**Closed by Mizux** 2018-09-05 09:52 UTC
Labels: C++, Help Needed, Routing
