### ISSUE TITLE
How to use Ortools and Visual Studio

### ISSUE THREAD

**Issue by philippe3263** [google/or-tools#1447] opened 2019-07-24 09:31 UTC
Hi,
We spent time to make a Visual Studio project with ORtools.

Here you can find a full Visual Studio Solution fully configure.

https://github.com/philippe3263/ORTools_Visual_Studio

Warning : change the link to the ORtools library (linker option to .lib) and the link to the header (compile option)

**Comment by lperron** [comment] 2019-08-07 01:01
Duplicate of #1449

**Closed by lperron** 2019-08-07 01:01 UTC
Labels: OS: Windows
