### ISSUE TITLE
Add Python 3.8 support

### ISSUE THREAD

**Issue by sameer** [google/or-tools#1719] opened 2019-11-14 17:25 UTC
Hello, are there plans to support Python 3.8 with the next release?
Mizux: yes target v7.5 release this month

Task Coding:
* [x] Update the docker stuff to build the python package on Linux
* [x] Update the release script on MacOS and
* [x] Update the release script on Windows 

Task infra:
* [x]  Update the mac release machine to add support to python 3.8
* [x] Update the Windows VM release machine to add support for python 3.8

**Comment by stradivari96** [comment] 2019-11-14 17:51
Duplicate of https://github.com/google/or-tools/issues/1702
> should be next release.

**Comment by Mizux** [comment] 2020-01-07 09:06
Reopen it to track the advancement...

**Comment by Mizux** [comment] 2020-01-07 16:09
https://github.com/google/or-tools/commit/4021c4ec517ba5c4bcfcb0923dcd873da3b8fa30

**Closed** 2020-01-15 07:53 UTC
Labels: Build: CMake, Build: Makefile, Feature Request, Lang: Python
