### ISSUE TITLE
  google or-tool run time error - "A fatal error has been detected by the Java Runtime Environment"

### ISSUE THREAD

**Issue by ChathurikaA** [google/or-tools#686] opened 2018-05-09 07:50 UTC
Hi,
* I am currently using google or-tool for my research project. When I run my coded program using google or-tool I have encountered following error.  (Window 10 x64 machine)
```
 A fatal error has been detected by the Java Runtime Environment:
  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffcd5f1ce93, pid=972, tid=1280

 JRE version: Java(TM) SE Runtime Environment (9.0+11) (build 9.0.4+11)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (9.0.4+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
 Problematic frame:
 C  [jniortools.dll+0x14ce93]
```
 No core dump will be written. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 `D:\SMU\GoogleORtool\ortoolsVisualStudi\ortoolsVisualStudio\hs_err_pid972.log`

If you would like to submit a bug report, please visit:
  http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

* Further, I have tried same code in Ubuntu-14.04 and I got some what slimier error as follows. 
```sh
 java -Djava.library.path=lib -cp objs:lib/com.google.ortools.jar:lib/protobuf.jar RunSolver 
```

```
 A fatal error has been detected by the Java Runtime Environment:
  SIGSEGV (0xb) at pc=0x00002ba0da7ab530, pid=11245, tid=0x00002ba0baa0d700

  JRE version: Java(TM) SE Runtime Environment (8.0_161-b12) (build 1.8.0_161-b12)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libortools.so+0x7a2530]  operations_research::Solver::MakeIntVar(std::vector<long long, std::allocator<long long> > const&, std::string const&)+0x1e0

 Core dump written. Default location: /home/chathurika/Google-OR-tool/or-tools_Ubuntu-14.04-64bit_v6.7.4973/core or core.11245
```
 
An error report file with more information is saved as:
` /home/chathurika/Google-OR-tool/or-tools_Ubuntu-14.04-64bit_v6.7.4973/hs_err_pid11245.log`
    
* By further examine, I realized that the program is terminated as above after adding few constraints.
Could you please help me to fix the error?

**Comment by Mizux** [comment] 2018-05-09 09:38
Hi, did you first try to run some [java samples](https://github.com/google/or-tools/tree/master/examples/com/google/ortools/samples) to see if your installation is working ?

**Comment by Mizux** [comment] 2019-01-31 14:03
If you have a minimal test to reproduce the error, it may help us a lot to help you !

**Comment by lperron** [comment] 2019-08-06 16:53
Duplicate of #272

**Closed by lperron** 2019-08-06 16:53 UTC
Labels: Help Needed, Lang: Java, OS: Linux, OS: Windows
