### ISSUE TITLE
const member function already defined or declared (flag.h)

### ISSUE THREAD

**Issue by Regista6** [google/or-tools#3247] opened 2022-04-15 16:39 UTC
Hello,

-> I have downloaded and linked the directory of v9.3 of or-tools visual studio 2019 64bit. 

-> When I compile a simple program from the or-tools guide like LP solver, I am getting the following error:

     Severity   Code	Description	Project	File	Line	Suppression State
     Error	C2535	'void absl::lts_20211102::flags_internal::FlagImpl::Read(T *) const': member function already defined or 
     declared  or_tools_3	D:\or_tools_2\or-tools_VisualStudio2019-64bit_v9.3.10497\absl\flags\internal\flag.h	467	

Language used: C++17

**Comment by Mizux** [comment] 2022-04-15 17:35
Strange...
1) How did you get ortools using the visual studio 2019 archive ?
2) Which build system did you use for your simple program ?

**Comment by Regista6** [comment] 2022-04-15 17:53
Thank you for the reply.

1.  - I download 'Windows with Visual Studio 2019' from https://developers.google.com/optimization/install/cpp/windows.

   -   Then Included the path in the 'Include Directories' option in VS 2019.  This seemed to do the trick of recognizing the header files.
  
2. I am not so familiar with build systems. I think I am using the default build system.

**Comment by Mizux** [comment] 2022-04-20 10:57
IIRC
1. archive have been built using c++20 dialect, I don't know if it can impact and being the root cause but...
2. I'm working for v9.4 to provide C++ archives with CMake support (for the library and the examples wil comes with an accompanied `CMakeLists.txt`). So it should be easy to reproduce and find the root cause IMHO...

**Comment by Mizux** [comment] 2022-08-16 12:38
no update -> closing

**Closed by Mizux** 2022-08-16 12:38 UTC
Labels: Bug, Help Needed, OS: Windows, Lang: C++
