### ISSUE TITLE
Feasible solution not returned

### ISSUE THREAD

**Issue by amih77** [google/or-tools#1755] opened 2019-12-01 13:13 UTC
I've been working with or-tools for a few months now but recently experienced the following miss:

**Model:**
2 vehicles (each one has a start location `s0, s1` and an end location `t0, t1`)
2 locations `x0, x1`.

**Time windows:** 
```
[[5400, 5820], [9000, 9420], [5520, 39719], [6420, 43319], [5521, 39720], [6421, 43320]]
```

**Durations matrix:** 
```
[
   x0: [0, horizon, horizon, horizon, 5400, 5400], 
   x1: [horizon, 0, horizon, horizon, 1800, 1800], 
   s0: [0, 0, horizon, horizon, 0, horizon], 
   s1: [0, 0, horizon, horizon, horizon, 0], 
   t0: [horizon, horizon, horizon, horizon, horizon, horizon],
   t1: [horizon, horizon, horizon, horizon, horizon, horizon]
]
```
Where `horizon = 86760`.

I get `None` when I pass it to the solver. Not sure why the solver doesn't return the trivial feasible solution (which is `s_i -> x_i -> t_i` for `i=0, 1`). I'm using `PARALLEL_CHEAPEST_INSERTION` as it gives better solutions for my purposes than `PATH_CHEAPEST_ARC`.

Thanks.

**Comment by Mizux** [comment] 2019-12-03 17:06
duplicate of https://stackoverflow.com/questions/59127131/vrptw-or-tools-does-not-return-a-feasible-solution-in-a-very-simple-case ?

**Comment by Mizux** [comment] 2021-03-22 17:12
did you try to give your solution as "initial solution" to verify it's working ?

**Closed** 2021-12-07 12:21 UTC
Labels: Bug, Lang: Python, Solver: Routing Solver
