### ISSUE TITLE
mixed_integer_programming's result isn't global optimum(for .NET)

### ISSUE THREAD

**Issue by orwant** [google/or-tools#41] opened 2015-08-05 13:59 UTC
Originally reported on Google Code with ID 25
```
mixed_integer_programming's solution isn't global optimum(for .NET)

Thanks for your attention!

I'm trying to solve a mixed-integer problem with orTools like the example csintegerprogramming.cs.
The objective function and the constraints are all linear.
When I solved it with CBC_MIXED_INTEGER_PROGRAMMING or other methods,then I got one
result(this is the first result).
But when I change the first result into a new constraint and add it into the problem
above.Then I get a second result,I found that the sencond result is better then the
first one. 
So, I think I got a locally optimal solution.
How can I solve this problem?


```

Reported by `mwzh2520` on 2013-05-16 08:23:31

**Comment by lperron** [comment] 2016-01-06 13:48
likely a bug in the underlying solver.
Closing the bug as I cannot reproduce it.

**Closed by lperron** 2016-01-06 13:48 UTC
Labels: Priority-Medium, Status-New, Type-Defect
