### ISSUE TITLE
ortools once-off crash

### ISSUE THREAD

**Issue by andreas-sakellariou** [google/or-tools#2272] opened 2020-12-04 11:54 UTC
**What version of OR-tools and what language are you using?**
Version: 8.0.8283
Language: Python 3.8.5

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04

**What did you do?**
Nothing special. I have run the code dozens of times in the mentioned platform as well as in Windows 10x64. It is the first time I encounter this issue. The code used 12 workers (out of 64 available). Timeout was set to 360000 sec.
After the error I run it again without any change and still runs.

**What did you expect to see**
The code should run until timeout or until Optimal solution or until killed by OOM

**What did you see instead?**
[Proto.txt](https://github.com/google/or-tools/files/5642521/Proto.txt)

Full Error message 
Check failed: AttachAndPropagate(clause, trail)
*** Check failure stack trace: ***
    @     0x7f2cecd5438d  google::LogMessage::Fail()
    @     0x7f2cecd57c85  google::LogMessage::SendToLog()
    @     0x7f2cecd53fcd  google::LogMessage::Flush()
    @     0x7f2cecd55129  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2cec84f8ea  operations_research::sat::LiteralWatchers::AddRemovableClause()
    @     0x7f2ceca2b13a  operations_research::sat::SatSolver::AddLearnedClauseAndEnqueueUnitPropagation()
    @     0x7f2ceca2bb33  operations_research::sat::SatSolver::PropagateAndStopAfterOneConflictResolution()
    @     0x7f2ceca2d6f1  operations_research::sat::SatSolver::EnqueueDecisionAndBackjumpOnConflict()
    @     0x7f2cec987b98  operations_research::sat::SolveIntegerProblem()
    @     0x7f2cec9d309c  operations_research::sat::MinimizeIntegerVariableWithLinearScanAndLazyEncoding()
    @     0x7f2cec8f6237  operations_research::sat::(anonymous namespace)::SolveLoadedCpModel()
    @     0x7f2cec8fe52a  _ZNSt17_Function_handlerIFvvEZN19operations_research3sat12_GLOBAL__N_117FullProblemSolver12GenerateTaskElEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x7f2ceca46f8c  _ZNSt17_Function_handlerIFvvEZN19operations_research3sat20NonDeterministicLoopERKSt6vectorISt10unique_ptrINS2_9SubSolverESt14default_deleteIS5_EESaIS8_EEiEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x7f2cec701e78  operations_research::RunWorker()
    @     0x7f2ced89a93f  execute_native_thread_routine
    @     0x7f2cef2ac609  start_thread
    @     0x7f2cef3e8293  clone
    @              (nil)  (unknown)
Aborted

**Anything else we should know about your project / environment**

ortools==8.0.8283
protobuf==3.14.0

**Comment by lperron** [comment] 2021-12-07 12:00
Cannot reproduce. CLosing. Please reopen if needed.

**Closed by lperron** 2021-12-07 12:00 UTC
Labels: Bug, Lang: Python, Solver: CP-SAT Solver
