### ISSUE TITLE
Add support for Go to the Linear Solver

### ISSUE THREAD

**Issue by sauterp** [google/or-tools#1881] opened 2020-02-13 03:32 UTC
**What language and solver does this apply to?**
Go; Linear Solver

**Describe the problem you are trying to solve.**
I wanted to use the Linear Solver in a Go application on Windows and Linux.

**Describe the solution you'd like**
I [forked OR-Tools](https://github.com/sauterp/or-tools/tree/gosupport) and converted the SWIG interface for the linear_solver component for Python to work with Go. The build process works on Windows and [I documented it here](https://gist.github.com/sauterp/b6953c2804ce77962964e4fcab19679a).

**Describe alternatives you've considered**
I am not aware of any Go package that allows you to setup and solve linear optimization models conveniently and with a unified interface for different solvers. There have been two good attempts:
- https://github.com/lanl/clp
- https://github.com/draffensperger/golp

**Additional context**
My use case:
I work with heuristics for some NP-hard problems. It's easy to implement a program in Python to solve **one** LP. But if I want to solve N^2 smaller LPs for example, the Python overhead becomes very noticeable. With Go, I can get better performance and I can deploy my work on other systems with minimal dependencies. An advantage over C++ in this case is that others can reuse or maintain my work more easily.

**Comment by Mizux** [comment] 2020-02-13 06:55
duplicate of #953

**Comment by gonzojive** [comment] 2020-05-26 08:18
I took a stab at this in a small project that builds with Bazel: https://github.com/gonzojive/or-tools-go

I don't know a lot about C and C++ toolchains, and makefiles, so Bazel was the simplest way to get it working for me. I will follow up in #953 instead to see about merging the project into the official or tools repo.

**Comment by lperron** [comment] 2023-08-10 22:16
Duplicate of #953

**Closed by lperron** 2023-08-10 22:16 UTC
Labels: Duplicate, Feature Request, OS: Windows, OS: Linux, OS: Mac
