### ISSUE TITLE
Or-tools failed to run cxx_cpp_pdlp_solve test on release and debug configuration with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [google/or-tools#3473] opened 2022-09-26 07:26 UTC
Hi All,

Environment:
VS 2019 + Windows Server 2019

Or-tools failed to run cxx_cpp_pdlp_solve test on release and debug configuration with MSVC on windows. it can be reproduced on 82750ac on stable branch. Could you please help look at this issue?

Repro steps:
1. git clone https://github.com/google/or-tools F:\gitP\google\or-tools
2. cd F:\gitP\google\or-tools && mkdir build_amd64 && cd build_amd64
3. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=Debug ..
4. cmake --build . --config Debug --target ALL_BUILD -v -- /maxcpucount
5. ctest --build-config Debug --output-on-failure -R "cxx_cpp_pdlp_solve"

Error info:
Test project F:/gitP/google/or-tools/build_debug_amd64
    Start 99: cxx_cpp_pdlp_solve
1/1 Test #99: cxx_cpp_pdlp_solve ...............***Failed    2.96 sec
F0926 00:25:49.071683 12384 pdlp_solve.cc:76] Check failed: !input.empty() --input is required
*** Check failure stack trace: ***
    @   00007FF6847D3BFC  (unknown)
    @   00007FF6847D3B29  (unknown)
    @   00007FF6847D33FA  (unknown)
    @   00007FF6847D4D94  (unknown)
    @   00007FF6847C251F  (unknown)
    @   00007FF6847C2ED0  (unknown)
    @   00007FF684F27869  (unknown)
    @   00007FF684F2770E  (unknown)
    @   00007FF684F275CE  (unknown)
    @   00007FF684F278FE  (unknown)
    @   00007FFF497A4ED0  (unknown)
    @   00007FFF4B85E39B  (unknown)

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   2.98 sec

The following tests FAILED:
         99 - cxx_cpp_pdlp_solve (Failed)
Errors while running CTest

**Comment by Mizux** [comment] 2022-09-26 07:36
this executable need some options on the command line but we currently use a cmake macro to loop over all exmaples and this macro can't take cli options yet...

**Comment by lperron** [comment] 2022-09-26 12:37
duplicate of #3429

**Closed by lperron** 2022-09-26 12:37 UTC
Labels: Bug, Lang: C++
