### ISSUE TITLE
Python wheel build failure in windows 11 x64 (main branch)

### ISSUE THREAD

**Issue by arnabadas** [google/or-tools#3806] opened 2023-06-02 07:15 UTC
**What version of OR-Tools and what language are you using?**
Version: main/v9.6/v9.5 etc.
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
All

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
Build ortools python wheel from source

**What did you expect to see**
Successful build

**What did you see instead?**
Failed build
[trace.txt](https://github.com/google/or-tools/files/11632873/trace.txt)

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
VS2022 latest, all python libs updated.

**Comment by lperron** [comment] 2023-06-02 07:31
Internal compiler error.

**Comment by Mizux** [comment] 2023-06-02 07:37
closing it as duplicate of:
* #3807

**Closed by Mizux** 2023-06-02 07:37 UTC
Labels: Bug, Duplicate, OS: Windows
