### ISSUE TITLE
CPSolver does not handle 64 Bit Constants

### ISSUE THREAD

**Issue by cgerum** [google/or-tools#2343] opened 2021-01-17 00:18 UTC
**What version of OR-tools and what language are you using?**
Version: 8.1.8487
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

CP-SAT

**What operating system (Linux, Windows, ...) and version?**

Linux, Ubuntu 20.04

**What did you do?**

When running the following code the solver Produces result Infeasible: 

`
from ortools.sat.python import cp_model

model = cp_model.CpModel()
v1 = model.NewConstant(0x0)
v2 = model.NewConstant(0x800000000)

print("v1", v1)
print("v2", v2)
model.AddAllDifferent([v1, v2])

solver = cp_model.CpSolver()
solver.Solve(model)
print(solver.StatusName())
` 

**What did you expect to see**

If 64_Bit where handled correctly it should result in solver status being OPTIMAL.

**What did you see instead?**

It produced result INFEASIBLE.

**Comment by stradivari96** [comment] 2021-01-17 01:26
If you enable `solver.parameters.log_search_progress = True` you see:
> var #1 domain do not fall in [kint64min + 2, kint64max - 1]

Maybe it would be good to add this:
```
assert domain.Min() >= INT_MIN+2
assert domain.Max() <= INT_MAX-1
```
here
https://github.com/google/or-tools/blob/252564060e3ac14bf3be7e4da1fde8f901e82310/ortools/sat/python/cp_model.py#L454-L461

**Comment by cgerum** [comment] 2021-01-17 02:12
> If you enable `solver.parameters.log_search_progress = True` you see:
> 
> > var #1 domain do not fall in [kint64min + 2, kint64max - 1]

Thanks for the tip, but I also could not reproduce that error message. 
My variables seem to be within [kint64min+2, kin64max-1] as well: 

https://github.com/google/or-tools/blob/252564060e3ac14bf3be7e4da1fde8f901e82310/ortools/base/integral_types.h#L60

**Comment by lperron** [comment] 2021-01-17 05:52
The solver aggressively checks that the model will not overflow.

If you call ValidateModel on it, it should print the right message.

This is by design.

Le dim. 17 janv. 2021 à 03:13, Christoph Gerum <notifications@github.com> a
écrit :

**Comment by lperron** [comment] 2021-01-17 05:54
Leg me check. Maybe the python layer has a wrong int/int64 cast in its code
path.

**Comment by lperron** [comment] 2021-01-17 09:26
Thanks for the report. It was indeed an overflow in the constant caching code. 
I pushed the fix to master.

**Closed** 2021-01-17 09:26 UTC
