### ISSUE TITLE
usage of addDifferent method produce invalid model in CpSat

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#1464] opened 2019-07-30 15:10 UTC
Hello,
 I tried to formulate inequality in java and found method CpModel.addDifferent. Unfortunatelly usage of the method always lead to invalid model.
 There's a small example with same result.

        CpModel cpModel = new CpModel();
        IntVar endVar = cpModel.newIntVar(0, 100, "end");
        cpModel.addDifferent(endVar, 50);

        CpSolver cpSolver = new CpSolver();
        cpSolver.getParameters().setLogSearchProgress(true);

        cpSolver.solveWithSolutionCallback(cpModel, new CpSolverSolutionCallback()
        {
            @Override
            public void onSolutionCallback()
            {
                System.out.println("solution found");
            }
        });

and there's a result

Parameters: log_search_progress: true
Invalid domain in constraint #0 : linear { vars: 0 coeffs: 1 domain: 0 domain: 49 domain: 51 domain: -1 }
CpSolverResponse:
status: MODEL_INVALID
objective: NA
best_bound: NA
booleans: 0
conflicts: 0
branches: 0
propagations: 0
integer_propagations: 0
walltime: 0
usertime: 0
deterministic_time: 0

**Comment by stradivari96** [comment] 2019-07-30 15:16
Sounds like a duplicate of #1448

**Comment by gregy4** [comment] 2019-07-30 15:23
Thanks.
Issues are close, but different methods are used and my case is produced invalid model so I get no valid or invalid solutions :-)

**Comment by lperron** [comment] 2019-07-30 16:14
Can you print the proto ?

model.build().toString() ?

I suppose this is the same issue.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by gregy4** [comment] 2019-07-30 20:23
variables {
  name: "end"
  domain: 0
  domain: 100
}
constraints {
  linear {
    vars: 0
    coeffs: 1
    domain: 0
    domain: 49
    domain: 51
    domain: -1
  }
}

**Comment by lperron** [comment] 2019-07-30 21:32
yep, same bug.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Closed** 2019-07-30 22:22 UTC
