### ISSUE TITLE
Build fails when trying to install from source code ( or tools v9.0)

### ISSUE THREAD

**Issue by Sai-Chandar** [google/or-tools#3508] opened 2022-10-20 07:11 UTC
**What version of OR-Tools and what language are you using?**
Version: v9.0
Language: 
C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
I'm trying to get CBC working on v9.0.

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**

I tried building the package using Cmake and the following commands. I'm trying to build v9.0 since our systems use an older .NET version and it's easier to build or-tools v9.0 than to upgrade the .NET version to 6.0. 

```sh
cmake -S. -Bbuild -DBUILD_DOTNET=ON
cmake --build build --config Release -j -v
```

The build fails when trying to compile a C++ file in or-tools-9.0\ortools\graph\max_flow.cc. With the following error:

`Build FAILED.

       "C:\Users\nainisai\temp\older_version\or-tools-9.0\or-tools-9.0\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "C:\Users\nainisai\temp\older_version\or-tools-9.0\or-tools-9.0\build\examples\dotnet\dotnet_example_NetworkRout
       ingSat.vcxproj" (default target) (3) ->
       "C:\Users\nainisai\temp\older_version\or-tools-9.0\or-tools-9.0\build\dotnet_package.vcxproj" (default target) (
       4) ->
       "C:\Users\nainisai\temp\older_version\or-tools-9.0\or-tools-9.0\build\dotnet_native.vcxproj" (default target) (5
       ) ->
       "C:\Users\nainisai\temp\older_version\or-tools-9.0\or-tools-9.0\build\Dotnetortools_proto.vcxproj" (default targ
       et) (6) ->
       "C:\Users\nainisai\temp\older_version\or-tools-9.0\or-tools-9.0\build\ortools.vcxproj" (default target) (13) ->
       "C:\Users\nainisai\temp\older_version\or-tools-9.0\or-tools-9.0\build\ortools\graph\ortools_graph.vcxproj" (defa
       ult target) (34) ->
       (ClCompile target) ->
         C:\Users\nainisai\temp\older_version\or-tools-9.0\or-tools-9.0\ortools\graph\max_flow.cc(927,43): error C2374:
        'kMaxFlowQuantity': redefinition; multiple initialization [C:\Users\nainisai\temp\older_version\or-tools-9.0\or
       -tools-9.0\build\ortools\graph\ortools_graph.vcxproj]

    0 Warning(s)
    1 Error(s)`

**What did you see instead?**
![image](https://user-images.githubusercontent.com/50066371/196879064-f4d10bd4-cab4-43b2-b431-7fe543199f4f.png)

Thank you!

**Comment by lperron** [comment] 2022-10-20 09:35
1. CBC is included. Why recompile ?
2. You can compile with .NET 3.1
3. which compiler are you using ?

**Comment by CADBIMDeveloper** [comment] 2022-10-21 08:40
Hi guys,

I also faced exactly the same issue a year ago. v9.0 sources requires to be compiled with VS 2017. It didn't work on my VS 2019 version and I believe it also doesn't work in VS 2022.

This issue was fixed later

**Comment by Mizux** [comment] 2022-10-21 08:58
duplicate of #2557 which was fixed by https://github.com/google/or-tools/commit/da45c9da3ca0eab720ac901ef376f9b87eb6c58d ?

**Closed by Mizux** 2022-10-21 08:58 UTC
