### ISSUE TITLE
multiple initialization in ortools\graph\max_flow.cc

### ISSUE THREAD

**Issue by toohes** [google/or-tools#2557] opened 2021-05-18 12:32 UTC
Version: stable(b37d9c786b69128f3505f15beca09e89bf078a89).
Language: C++ (Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29915 for x64)
OS: Windows 10

1. Call `cl /I. /Iortools/gen /Idependencies\install\include -c ortools\graph\max_flow.cc`
2. See error
```
.\ortools\graph\max_flow.cc(927): error C2374: 'kMaxFlowQuantity': redefinition; multiple initialization
.\ortools\graph\max_flow.cc(927): note: see declaration of 'kMaxFlowQuantity'
.\ortools\graph\max_flow.cc(928): note: while compiling class template static data member 'const operations_research::FlowQuantity operations_research::GenericMaxFlow<operations_research::SimpleMaxFlow::Graph>::kMaxFlowQuantity'
.\ortools\graph\max_flow.cc(78): note: see reference to class template instantiation 'operations_research::GenericMaxFlow<operations_research::SimpleMaxFlow::Graph>' being compiled
```

max_flow.cc(984):
```
// Explicit instanciations that can be used by a client.
//
// TODO(user): moves this code out of a .cc file and include it at the end of
// the header so it can work with any graph implementation ?
template class GenericMaxFlow<StarGraph>;
template class GenericMaxFlow<::util::ReverseArcListGraph<>>;
template class GenericMaxFlow<::util::ReverseArcStaticGraph<>>;
template class GenericMaxFlow<::util::ReverseArcMixedGraph<>>;
```
All these classes are already instantiated above in the same file.
Removal helps.

**Comment by lperron** [comment] 2021-05-18 12:40
are you building in c++ 17 mode ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Mizux** [comment] 2021-05-18 12:41
Did you try to build using one of the three build system ? You command line seems very short without all options, compile definition, C++17 enabled etc we usually found when using the provided build system config

**Comment by toohes** [comment] 2021-05-18 12:58
I catched it on cmake and tools\make cc

**Comment by toohes** [comment] 2021-05-18 14:11
this works for me
[patch.zip](https://github.com/google/or-tools/files/6501945/patch.zip)

**Comment by lperron** [comment] 2021-05-18 14:24
This does not work on all compilers.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by toohes** [comment] 2021-05-18 14:43
[c++17 required](https://en.cppreference.com/w/cpp/language/inline)

**Comment by Mizux** [comment] 2021-06-03 16:34
Can't reproduce it with "C++ (Microsoft (R) C/C++ Optimizing Compiler Version **19.28.29337** for x64"
on my way to upgrade the compiler and test it again

**Comment by SanPen** [comment] 2021-08-12 16:19
Adding 

```
template<> const FlowQuantity GenericMaxFlow<StarGraph>::kMaxFlowQuantity = std::numeric_limits<FlowQuantity>::max();
template<> const FlowQuantity GenericMaxFlow<::util::ReverseArcListGraph<>>::kMaxFlowQuantity = std::numeric_limits<FlowQuantity>::max();
template<> const FlowQuantity GenericMaxFlow<::util::ReverseArcStaticGraph<>>::kMaxFlowQuantity = std::numeric_limits<FlowQuantity>::max();
template<> const FlowQuantity GenericMaxFlow<::util::ReverseArcMixedGraph<>>::kMaxFlowQuantity = std::numeric_limits<FlowQuantity>::max();

```

to `max_flow.cc ` solves the issue for me.

**Comment by lperron** [comment] 2021-08-12 20:24
Already fixed on master.

**Comment by Mizux** [comment] 2021-08-13 07:08
Fixed by https://github.com/google/or-tools/commit/9a33a684764de85dd90f684b19aaacd2c7856368

**Closed by Mizux** 2021-08-13 07:08 UTC
Labels: Bug, OS: Windows, Lang: C++
