### ISSUE TITLE
Crash of cp-sat solver

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#1194] opened 2019-04-16 15:27 UTC
Solver crashed today with following message :
F0416 16:21:57.700780 15516 sat_solver.cc:1674] Check failed: !Assignment().VariableIsAssigned(literal.Variable())

Unfortunatelly it is not easy to reproduce it, since it fails only rarely. Hopefully it will be possible in next days.

I found the error on master branch of or-tools created short time after release of 7.0.6546 since I tested fix for #1163. So about 2 weeks old.

**Comment by lperron** [comment] 2019-04-16 15:30
We have fixed a lot of bugs since 7.0

I will close the issue, unless you can reproduce it.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Closed** 2019-04-16 15:30 UTC

**Comment by gregy4** [comment] 2019-04-18 08:50
I build or-tools from current master branch on Wednesday morning and so far no crash. Highly probably the problem was solved in previous two weeks.
