### ISSUE TITLE
Deliver right after picking up

### ISSUE THREAD

**Issue by lcluz** [google/or-tools#1764] opened 2019-12-04 16:54 UTC
Hi,
I am trying to solve a problem in which two vehicles have to travel to several pick and delivery points, but after picking up the next destination should be the correspondent delivery one.
One idea that I had was to define the max capacity of each vehicle to 1 and the demand capacity at each pick up place would be 1 as well, getting this data formulation:
    data['pickups_deliveries'] = [
        [1, 8],
        [2, 9],
        [3, 10],
        [4, 7],
        [5, 11],
        [6, 11],
    ]
    data['demands'] = [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    data['vehicle_capacities'] = [1, 1]
    data['num_vehicles'] = 2
    data['depot'] = 0
This didn't work out, assignment turned out to be None, which I guess means that there is no solution.
Anyone has any idea on how to do this or what can I change in the original CVRP or PDVRP (basically just put them together and changed the data) to deal with this possible solution.

Thanks in advance!

**Comment by FNanni** [comment] 2019-12-04 17:10
The demand at each delivery node should be -1, i.e. the vehicle has to unload what was loaded at the pickup node.

**Comment by FNanni** [comment] 2019-12-04 17:13
An alternative that doesn't involve setting the vehicles capacities to 1 could be to add this constraint to each pickup-delivery pair:
`routing.solver().Add(routing.NextVar(pickup_index) == delivery_index)`

**Comment by lcluz** [comment] 2019-12-04 17:14
Hi @FNanni,
Thanks for your reply. I get that and I actually tried that before. Anyways, just tried it again and got the same None in the assignment variable.

**Comment by lcluz** [comment] 2019-12-04 17:35
Didn't seem to work, still getting the same output.

**Comment by lcluz** [comment] 2019-12-04 17:39
Actually it worked once I removed the last "data['pickups_deliveries']" entry, which means that two different pickup points can't have the same delivery. Any tips on how to solve that?

**Comment by FNanni** [comment] 2019-12-04 17:59
I didn't notice the duplicated delivery points. I think you are right! Just try creating a duplicate of 11 so that: 5 --> 11 and 6 --> 12. Did you try that?

**Comment by lcluz** [comment] 2019-12-05 08:48
Hey @FNanni that did the trick! kind of hacky, but I think it will work for now. thanks for your help!

**Closed** 2019-12-05 08:56 UTC
