### ISSUE TITLE
How does the CP-SAT solver works?

### ISSUE THREAD

**Issue by tanishqvyas** [google/or-tools#1508] opened 2019-08-20 14:48 UTC
Could anyone provide with an explanation on how does the CP-SAT solver (used in constraint programming) works or any leads to the underlying algorithms and principles.

**Comment by stradivari96** [comment] 2019-08-20 16:19
https://stackoverflow.com/questions/57123397/which-solver-do-googles-or-tools-modules-for-csp-and-vrp-use/57125734#57125734

**Comment by lperron** [comment] 2019-08-20 17:19
Duplicate of #920

**Closed by lperron** 2019-08-20 17:19 UTC
