### ISSUE TITLE
Runtime error - [Cp-SAT; v. 7.5; Java & Python; Windows 10]

### ISSUE THREAD

**Issue by prissky** [google/or-tools#1864] opened 2020-01-31 15:29 UTC
Hello,

when loading and solving a protofile attached bellow, most of the time, I get

**A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa1d407932, pid=10700, tid=0x0000000000002aac
JRE version: Java(TM) SE Runtime Environment (8.0_202-b08) (build 1.8.0_202-b08)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [jniortools.dll+0xa17932]**

[problem_2020_01_31.zip](https://github.com/google/or-tools/files/4140041/problem_2020_01_31.zip)

Just to be sure to detect the error, I launch the solve multiple times as follows:

```java
for (int i = 0; i < 100; i++) {
        InputStream targetStream;
        CpModel model = new CpModel();
        try {
            targetStream = new FileInputStream(new File("c:/temp/problem_2020_01_31.proto"));
            model.getBuilder().mergeFrom(targetStream);
        } catch (IOException e) {
            e.printStackTrace();
        }
        CpSolver cpSolver = new CpSolver();
        cpSolver.solve(model);
}
```

**Comment by lperron** [comment] 2020-02-05 10:06
Can you try with a garbage collect after each loop?
It looks like the GC is not keeping up with the memory pressure.

**Comment by prissky** [comment] 2020-02-05 12:39
Thank You for the response. No, requesting GC does not seem to affect the error distribution (it often occurs during the first iteration). The parallelization (numSearchWorkers), on the other hand, does.

**Comment by lperron** [comment] 2020-02-05 13:29
It works perfectly for me on master.
Did you increase the java max memory ?

**Comment by prissky** [comment] 2020-02-05 14:05
Yes; it did not help me either.

**Comment by prissky** [comment] 2020-02-11 15:38
The problem is also present on python. Its occurrence strongly depends on parallelism (e.g. solver.parameters.num_search_workers = 12).

[problem_2020_01_31_py.zip](https://github.com/google/or-tools/files/4186475/problem_2020_01_31_py.zip)

**Comment by crypto-rsa** [comment] 2020-02-22 17:10
I use the .NET wrapper of the CP-SAT solver and I also get `AccessViolationException` when running the solver with the `num_search_workers` parameter set.

**Comment by lperron** [comment] 2020-03-02 13:03
I cannot reproduce it on master.

So closing the issue.

Thanks for the report.

**Closed by lperron** 2020-03-02 13:03 UTC
Labels: Bug, Lang: Java, OS: Windows, Solver: CP / CP-SAT Solver
