### ISSUE TITLE
Building from source with SCIP

### ISSUE THREAD

**Issue by jacobparish** [google/or-tools#1023] opened 2019-01-20 22:40 UTC
Currently trying to build from source with the SCIP solver on OS X (following the instructions here: developers.google.com/optimization/install/python/source_mac). When I run `make python`, I get the following error:

    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [lib/libortools.dylib] Error 1

I'm running OS X 10.14.2, tried building both from master and from v6.10.

**Comment by Mizux** [comment] 2019-02-15 07:49
Did you use a precompiled version of SCIP ? The error message suggest you are using a wrong architecture for some libraries. If we can have more details to help you...

**Comment by Mizux** [comment] 2019-03-08 09:13
you may be interested by https://github.com/google/or-tools/issues/948#issuecomment-442447342 and
https://github.com/google/or-tools/issues/759#issuecomment-469637557

**Comment by Mizux** [comment] 2019-04-24 08:31
Building SCIP 6.0.1 using cmake and the command:
```sh
cmake -H. -Bbuild -DSHARED=OFF -DGMP=OFF -DGCG=OFF -DSYM=none -DIPOPT=OFF -DZIMPL=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=$HOME/scip
cmake --build build --target install
export UNIX_SCIP_DIR=$HOME/scip
cd <ortools_root_path>
make cc
```

```sh
```

note: mark it as duplicate of #1115

**Closed** 2019-04-24 08:37 UTC
Labels: Bug, Build: Makefile, Duplicate, Lang: Python, OS: Mac, Solver: Linear Solver, Solver: SCIP
