### ISSUE TITLE
Pickup and delivery: group nodes pickup nodes by vehicles

### ISSUE THREAD

**Issue by abduakhatov** [google/or-tools#980] opened 2018-12-18 11:27 UTC
I integrated PDP in VRP with Time and Capacity constraints (also Pickup and Delivery). It is working as expected, but there is another feature to implement. Is it possible to assign specific pickup or delivery node to specific car (group nodes to specific). I used following https://github.com/google/or-tools/issues/703

```
routing.AddPickupAndDelivery(1, 2)
routing.solver().Add(routing.VehicleVar(1) == routing.VehicleVar(2))
```

Another question which may possibly be linked to the first one: 
How to tell optimizer that the pickup node is visited (This is used for the purpose, if node is visited, so picked up and needs to be delivered)

Thanx in advance

**Comment by Mizux** [comment] 2018-12-18 12:47
duplicate of #979

**Closed by Mizux** 2018-12-18 12:47 UTC
