### ISSUE TITLE
Segmentation fault in Github runs

### ISSUE THREAD

**Issue by arnabadas** [google/or-tools#4154] opened 2024-03-25 09:26 UTC
**What version of OR-Tools and what language are you using?**
Version: stable
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
Check test 282 in [amd64 Windows CMake Python Github runs](https://github.com/google/or-tools/actions/runs/8364256727/job/22899138962)

**What did you expect to see**
NA

**What did you see instead?**
NA

Make sure you include information that can help us debug (full error message, model Proto).
NA

**Anything else we should know about your project / environment**
NA

**Comment by lperron** [comment] 2024-03-25 09:57
duplicate of #4144 and #4149

**Closed by lperron** 2024-03-25 09:57 UTC
