### ISSUE TITLE
Bug in cvrp_reload.py example

### ISSUE THREAD

**Issue by jmarca** [google/or-tools#2264] opened 2020-12-02 19:09 UTC
**What version of OR-tools and what language are you using?**
Version: master, 8.0.8283
Language: Python

**Which solver are you using:**
 Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**

There is a bug in the  cvrp_reload.py example

The demands have been crafted to hit 15, which means that the "reload" works.

As written, the current output looks like:

```
python cvrp_reload.py 
Objective: 255672
dropped orders: [1]
Route for vehicle 0:
 0 Load(0) Time(0,0) -> 12 Load(0) Time(2,752) -> 18 Load(8) Time(45,795) -> 17 Load(12) Time(67,817) -> 16 Load(14) Time(85,828) -> 4 Load(15) Time(96,839) -> 14 Load(0) Time(173,916) -> 10 Load(1) Time(180,923) -> 11 Load(3) Time(192,935) -> 13 Load(7) Time(214,957) -> 5 Load(15) Time(257,1000) -> 0 Load(0) Time(332,1500)
Distance of the route: 2488m
Load of the route: 0
Time of the route: 332min

Route for vehicle 1:
 0 Load(0) Time(0,0) -> 6 Load(0) Time(75,907) -> 9 Load(1) Time(82,914) -> 8 Load(5) Time(103,935) -> 20 Load(7) Time(119,951) -> 3 Load(15) Time(168,1000) -> 0 Load(0) Time(243,1500)
Distance of the route: 2192m
Load of the route: 0
Time of the route: 243min

Route for vehicle 2:
 0 Load(0) Time(0,0) -> 19 Load(0) Time(10,906) -> 21 Load(4) Time(32,928) -> 15 Load(12) Time(76,972) -> 7 Load(14) Time(90,986) -> 2 Load(15) Time(104,1000) -> 0 Load(0) Time(179,1500)
Distance of the route: 2192m
Load of the route: 0
Time of the route: 179min

Total Distance of all routes: 6872m
Total Load of all routes: 0
Total Time of all routes: 754min
```

However, this is a special case.  If the demands are changed such that they cannot add up to 15, the reloading never happens.

1. Go to https://github.com/google/or-tools/blob/d8f1f6d54edbfdf292a4bc690b6c925b9d1d4527/ortools/constraint_solver/samples/cvrp_reload.py#L78

2. Change all the 1 values to 2 (to prevent any of the totals adding up to 15)

should look like:

```python
    data['demands'] = \
          [0, # depot
           -_capacity,
           -_capacity,
           -_capacity,
           -_capacity,
           -_capacity,
           2, 2, # 1, 2
           2, 4, # 3, 4
           2, 4, # 5, 6
           8, 8, # 7, 8
           2, 2, # 9,10
           2, 2, # 11,12
           4, 4, # 13, 14
           8, 8] # 15, 16
```
(Capacity is 15.  There is no possible way 8s, 4s, and 2s can add to 15, so load will *never* equal negative of capacity.)

3. run the modified program

(It will run forever because no disjunctions on nodes and it cannot visit the unload nodes)

4. modify the example to have disjunctions on all nodes

```python
def add_capacity_constraints(routing, manager, data, demand_evaluator_index):
   ...
    for node_index in range(6, len(data['demands'])):
        index = manager.NodeToIndex(node_index)
        routing.AddDisjunction([node_index], 100000)
```

5. Run program with disjunctions

```
python cvrp_reload_failingcase.py
Objective: 589980
dropped orders: [1, 2, 3, 4, 5, 9, 16, 20, 21]
Route for vehicle 0:
 0 Load(0) Time(0,0) -> 13 Load(0) Time(10,1416) -> 11 Load(8) Time(52,1458) -> 7 Load(12) Time(75,1481) -> 0 Load(14) Time(94,1500)
Distance of the route: 1552m
Load of the route: 14
Time of the route: 94min

Route for vehicle 1:
 0 Load(0) Time(0,0) -> 10 Load(0) Time(3,955) -> 6 Load(2) Time(75,971) -> 8 Load(4) Time(88,984) -> 12 Load(6) Time(104,1000) -> 0 Load(14) Time(146,1500)
Distance of the route: 1780m
Load of the route: 14
Time of the route: 146min

Route for vehicle 2:
 0 Load(0) Time(0,0) -> 17 Load(0) Time(5,926) -> 18 Load(2) Time(17,938) -> 19 Load(6) Time(41,962) -> 15 Load(10) Time(75,986) -> 14 Load(12) Time(89,1000) -> 0 Load(14) Time(101,1500)
Distance of the route: 1848m
Load of the route: 14
Time of the route: 101min

Total Distance of all routes: 5180m
Total Load of all routes: 42
Total Time of all routes: 341min
```

Note the output...the "reload nodes" (1, 2, 3, 4, 5) are all included in the dropped orders array

**The Fix**

The bug is that the capacity dimension is being constructed with zero slack, which is then **NOT MODIFIED AT ALL** with the subsequent calls to 

```python
    for node_index in [1, 2, 3, 4, 5]:
        index = manager.NodeToIndex(node_index)
        capacity_dimension.SlackVar(index).SetRange(0, vehicle_capacity) # This does nothing.  Equivalent to a null op
        routing.AddDisjunction([node_index], 0)
```

As I wrote up in this comment https://github.com/google/or-tools/issues/1127#issuecomment-530650808, the creation of a dimension with zero slack creates a IntConst of zero, NOT an IntVar.  IntConst has a broken implementation of SetRange that only fails if the current constant value is outside of the passed in range.

Checked versus master: https://github.com/google/or-tools/blob/61b892beeadc256421cd97d71add454abb44e856/ortools/constraint_solver/expressions.cc#L2572-L2576

```cpp
  void SetRange(int64 l, int64 u) override {
    if (l > value_ || u < value_) {
      solver()->Fail();
    }
  }
```

In my opinion, the correct implementation should be
```cpp
  void SetRange(int64 l, int64 u) override {
    if (l != value_ || u != value_) {
      solver()->Fail();
    }
  }
```

Or just solver()->Fail().  Why? Because if you pass it something like SetRange(15,15) it will pass, but otherwise it will fail, because you're doing the wrong thing (asking a constant to have a variable range).

The example should follow the recommendations of https://github.com/google/or-tools/issues/1127#issuecomment-505789508

The capacity dimension code should be constructed with Non-zero slack, and then slack set to zero for regular nodes.

Corrected code:

```python
def add_capacity_constraints(routing, manager, data, demand_evaluator_index):
    """Adds capacity constraint"""
    vehicle_capacity = data['vehicle_capacity']
    capacity = 'Capacity'
    routing.AddDimension(
        demand_evaluator_index,
        # slack = vehicle_capacity for reload nodes, so that
        # CumulVar = 10(current load) + -15(unload) + 5(slack) = 0. 
        vehicle_capacity, # slack  
        vehicle_capacity, # max value
        True,  # start cumul to zero
        capacity)
    # allow dropping of reload nodes
    for node_index in [1, 2, 3, 4, 5]:
        index = manager.NodeToIndex(node_index)
        routing.AddDisjunction([node_index], 0)

    # change the slack at regular pickup nodes to be zero, so
    # they get the correct amount picked up
    capacity_dimension = routing.GetDimensionOrDie(capacity)
    for node_index in range(6, len(data['demands'])):
        index = manager.NodeToIndex(node_index)
        capacity_dimension.SlackVar(index).SetMax(0)
        routing.AddDisjunction([node_index], 100000)
```

Also, the revised program must be run with 

```python
    search_parameters.local_search_metaheuristic = (routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH)
    search_parameters.time_limit.seconds = 2
```

Or else a node gets dropped.

**What did you expect to see**

Running the corrected code gives:

``` 
python cvrp_reload_fixed.py 
Objective: 272584
dropped orders: []
Route for vehicle 0:
 0 Load(0) Time(0,0) -> 14 Load(0) Time(2,32) -> 19 Load(2) Time(15,45) -> 13 Load(6) Time(38,68) -> 2 Load(14) Time(81,111) -> 16 Load(0) Time(162,192) -> 20 Load(2) Time(175,205) -> 18 Load(10) Time(220,250) -> 0 Load(14) Time(244,1500)
Distance of the route: 2648m
Load of the route: 14
Time of the route: 244min

Route for vehicle 1:
 0 Load(0) Time(0,0) -> 12 Load(0) Time(2,51) -> 3 Load(8) Time(44,93) -> 5 Load(0) Time(119,168) -> 4 Load(0) Time(194,243) -> 1 Load(0) Time(269,318) -> 21 Load(0) Time(351,400) -> 15 Load(8) Time(395,770) -> 7 Load(10) Time(409,784) -> 10 Load(12) Time(425,800) -> 0 Load(14) Time(438,1500)
Distance of the route: 2580m
Load of the route: 14
Time of the route: 438min

Route for vehicle 2:
 0 Load(0) Time(0,0) -> 17 Load(0) Time(5,150) -> 9 Load(2) Time(45,548) -> 8 Load(6) Time(66,569) -> 6 Load(8) Time(79,582) -> 11 Load(10) Time(97,600) -> 0 Load(14) Time(123,1500)
Distance of the route: 2556m
Load of the route: 14
Time of the route: 123min

Total Distance of all routes: 7784m
Total Load of all routes: 42
Total Time of all routes: 805min
```

**Comment by Mizux** [comment] 2020-12-02 19:41
IIRC this is an old bug, need to find the original one, I though it was "fixed" strange...

**Comment by Mizux** [comment] 2020-12-02 19:44
seems to be a duplicate of #1127 BTW thanks for the feedback I'll try to fix the sample ASAP.

IIRC it is a known API bug (I mean the slackVar being a cstVar if set to zero, leading to noop later if you try to change it)

**Comment by jmarca** [comment] 2020-12-02 20:37
Yep.  That's a bug that needs the Google team to decide whether to fix and possibly break old code, or leave as is

I'm submitting a fix in a little bit.

**Closed** 2020-12-02 23:23 UTC
Labels: Bug, Duplicate, Lang: Python, Solver: Routing Solver
