### ISSUE TITLE
Bugs in pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING?

### ISSUE THREAD

**Issue by mucun1988** [google/or-tools#827] opened 2018-08-23 15:25 UTC
I consistently get suboptimal solutions when solving simple mixed integer optimization problem using `or-tools`. I will much appreciate if somebody can help me investigate the root cause of it. 

E.g., one optimization problem solved is as follows:
```
max  24*B_00 + 40*B_01 + 79*B_02 + 23*B_10 + 48*B_11
s.t. 
      11*B_00 + 22*B_01 + 33*B_02 + 10*B_10 + 23*B_11 <= 37
      B_00 + B_01 + B_02 <= 1
      B_10 + B_11 <= 1
      B_00, B_01, B_02, B_10, B_11 are binary
```
and the optimal solution should be B_00=1, B_11=1 and the others are 0 with objective value as 72; however `ortools` outputs B_01=1, B_10=1 and the others are 0 with objective value as 63, which is clearly suboptimal. Even worse, the solver claims it finds the optimal solution.

It is really wired to observe this. I have also put my code below to reproduce my observation:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 20 10:02:11 2018

max  24*B_00 + 40*B_01 + 79*B_02 + 23*B_10 + 48*B_11
s.t. 
      11*B_00 + 22*B_01 + 33*B_02 + 10*B_10 + 23*B_11 <= 37
      B_00 + B_01 + B_02 <= 1
      B_10 + B_11 <= 1
      B_00, B_01, B_02, B_10, B_11 are binary
"""
from ortools.linear_solver import pywraplp

solver = pywraplp.Solver('SolveIntegerProblem',
                         pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)

b_00 = solver.IntVar(0.0, 1.0, 'b_00')
b_01 = solver.IntVar(0.0, 1.0, 'b_01')
b_02 = solver.IntVar(0.0, 1.0, 'b_02')
b_10 = solver.IntVar(0.0, 1.0, 'b_10')
b_11 = solver.IntVar(0.0, 1.0, 'b_11')


constraint1 = solver.Constraint(-solver.infinity(), 37)
constraint1.SetCoefficient(b_00, 11)
constraint1.SetCoefficient(b_01, 22)
constraint1.SetCoefficient(b_02, 33)
constraint1.SetCoefficient(b_10, 10)
constraint1.SetCoefficient(b_11, 23)


constraint2 = solver.Constraint(1, 1)
constraint2.SetCoefficient(b_00, 1)
constraint2.SetCoefficient(b_01, 1)
constraint2.SetCoefficient(b_02, 1)
constraint2.SetCoefficient(b_10, 0)
constraint2.SetCoefficient(b_11, 0)


constraint3 = solver.Constraint(1, 1)
constraint3.SetCoefficient(b_00, 0)
constraint3.SetCoefficient(b_01, 0)
constraint3.SetCoefficient(b_02, 0)
constraint3.SetCoefficient(b_10, 1)
constraint3.SetCoefficient(b_11, 1)


objective = solver.Objective()
objective.SetCoefficient(b_00, 24)
objective.SetCoefficient(b_01, 40)
objective.SetCoefficient(b_02, 79)
objective.SetCoefficient(b_10, 23)
objective.SetCoefficient(b_11, 48)
objective.SetMaximization()

result_status = solver.Solve()

assert result_status == pywraplp.Solver.OPTIMAL
assert solver.VerifySolution(1e-7, True)

print('Number of variables =', solver.NumVariables())
print('Number of constraints =', solver.NumConstraints())
print('Optimal objective value = %d' % solver.Objective().Value())
```
and here is the output:
```
Number of variables = 5
Number of constraints = 3
Optimal objective value = 63
```

Thanks,
Matt

**Comment by Mizux** [comment] 2018-08-23 15:45
seems to be a duplicate of #814

**Closed** 2018-08-31 11:16 UTC
Labels: Bug, Duplicate, Help Needed, Python
