### ISSUE TITLE
StackOverflow while adding a dimension in a RoutingModel  in  .Net

### ISSUE THREAD

**Issue by orwant** [google/or-tools#30] opened 2015-08-05 12:58 UTC
Originally reported on Google Code with ID 14
```
Here's the piece of code that gives me trouble:

    Public Class ContainerDimensiuneTimp
        Inherits NodeEvaluator2

        Dim Timpi()() As Double

        Public Sub New(_timpi()() As Double)
            Timpi = _timpi
        End Sub

        Public Overloads Function Run(nod1 As Integer, nod2 As Integer) As Long
            Return CLng(Timpi(nod1)(nod2) * 60)
        End Function
    End Class

  After Initialising the RouterModel as "rutare" and setting the cost,


        Dim TimesContainer As New ContainerDimensiuneTimp(_timpi)
        rutare.AddDimension(TimesContainer, 100, 24 * 3600, "T")

When calling "rutare.AddDimension(TimesContainer, 100, 24 * 3600, "T")" it throws a
StackOverflow.
```

Reported by `stefy1995` on 2012-09-10 15:05:33

**Comment by lperron** [comment] 2016-01-06 13:46
I cannot reproduce it. Closing the bug.

**Closed by lperron** 2016-01-06 13:46 UTC
Labels: Priority-Medium, Status-New, Type-Defect
