### ISSUE TITLE
different results for the same input

### ISSUE THREAD

**Issue by minaghavipour** [google/or-tools#1579] opened 2019-09-15 05:19 UTC
Surprisingly, I get different results for the same input when I run my python code several times.

**Comment by lperron** [comment] 2019-09-15 05:37
First, the is too vague, you do not describe the solver used, the platform,
the language.

Second, there are many reasons why it can happen,  for all solvers.

The obvious one is that the problem is not strictly the same. If you
iterate over hash maps, dictionaries, the order can vary. This can lead to
high variability.

It is also true that the parallel search of the CP-SAT solver is not
deterministic.

What is a bug is that you do not find the same objective value across runs.

I hope this helps.



Le dim. 15 sept. 2019 à 06:19, minaghavipour <notifications@github.com> a
écrit :

**Comment by minaghavipour** [comment] 2019-09-15 06:08
Thank you for your answer!
You're right. Let me explain the problem in more detail.
I use PyCharm and my programming language is python. My code is a pipeline of 4 solvers: 
The first is a CP solver which generates all feasible solutions for my input. 
The second is a CP-SAT solver which returns the optimal solution, using the outputs of the previous solver as its input. This solver filters some output solutions of the first solver and provides the input for the third solver.
The third is also a CP-SAT solver finding the optimal solution, considering the inputs provided by the previous solver.
Finally, the last solver is a MIP solver which finds the optimal solution based on the outputs of the previous solver.

Despite all solvers find the optimal solution (except for the first solver which generates all feasible solutions), the final result is different for the same input.

**Comment by stradivari96** [comment] 2019-09-15 07:59
Optimal just means that it maximizes or minimizes the objetive, so there can be many optimal solutions for each one of your problems.

**Comment by lperron** [comment] 2019-09-18 13:24
Can you track down where it starts to diverge in the flow ?

**Comment by lperron** [comment] 2019-10-01 06:52
Any news?

**Comment by lperron** [comment] 2020-09-22 08:48
Closing now. Dead for 1 year.

**Closed by lperron** 2020-09-22 08:48 UTC
Labels: Help Needed, Solver: CP / CP-SAT Solver

**Comment by brucefeng10** [comment] 2024-04-17 09:30
hello，
I'm solving a complex Integer Problem, and i use CP-SAT solver, which performs much much better than SCIP. But there are two questions:
1. Everytime i run the problem with the same input, the result is different. I mean the objective value is different, sometimes it varies much.
2. Since the CP-SAT solver doesn't have the optimal gap like B&B solver, is there any way to find how good the solution is? 
My platform is Java8
Thanks.

**Comment by lperron** [comment] 2024-04-17 09:33
do not revive an old bug.
Create a new one.
Indicate the version.
Attach the model.
CP-SAT has a gap. It reports objective lower and upper bounds. By default,
it only terminates with a gap of 0.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 17 avr. 2024 à 11:31, Bruce Feng ***@***.***> a
écrit :

**Comment by brucefeng10** [comment] 2024-04-18 10:22
OK，thanks
