### ISSUE TITLE
Protobuf "File already exists in database" error in osx

### ISSUE THREAD

**Issue by CaselIT** [google/or-tools#1830] opened 2020-01-07 11:09 UTC
Hi,

I'm getting this error using osx catalina with `ortools==7.4.7247` under python 3.7 while creating a model
```
[libprotobuf ERROR /Users/lperron/Work/or-tools/dependencies/sources/protobuf-3.10.0/src/google/protobuf/descriptor_database.cc:120] File already exists in database: proto3
[libprotobuf FATAL /Users/lperron/Work/or-tools/dependencies/sources/protobuf-3.10.0/src/google/protobuf/descriptor.cc:1359] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
```
The protobuf version is `protobuf==3.11.2`. Downgrading protobuf to version 3.10 has the same problem.
I've tried downgrading or-tools to versions 7.3.x, 7.2.x and 7.1.x and all have similar problems with protobuf (not exactly the same error, but it fails in the same point in my program). Version 7.0.x works correctly.

The program I'm running uses also tensorflow (version 1.13.1) and loads some models before using ortools. The same program works correctly under linux (ubuntu 18.04) and windows 10

Thank you

**Comment by CervEdin** [comment] 2020-01-07 11:23
Can't offer much help but it looks similar to this

https://superuser.com/questions/1491364/attempted-import-of-apache-beam-in-python3-on-mac-throws-fatal-protobuf-error

**Comment by CaselIT** [comment] 2020-01-07 11:32
It seems indeed similar, but I'm not using pyarrow (it is not installed in the env)

**Comment by CervEdin** [comment] 2020-01-07 11:34
maybe you're experiencing the same problem but with TF?

**Comment by CervEdin** [comment] 2020-01-07 11:36
fyi, here's another issue with protobuf/tf
https://github.com/google/or-tools/issues/681

**Comment by CaselIT** [comment] 2020-01-07 11:58
Thanks, I'll try checking if the solution in that issue works and/or fiddling with the import order.

Thanks

**Comment by CaselIT** [comment] 2020-01-07 13:03
So to reproduce just run
```python
import tensorflow
import ortools.linear_solver.pywraplp
```
inverting the imports seems to "fix" the issue

this is with `tensorflow==1.13.1`. I have not tried other versions

**Comment by Mizux** [comment] 2020-01-07 13:11
kind of duplicate of #1829
Long story python can only load one Protobuf native shared library so tensorflow and or-tools must be "in sync" please follow #1829 once done you may recompile or-tools from source and use this python package which will be based on the last Protobuf release...

**Closed by Mizux** 2020-01-07 13:11 UTC

**Comment by CaselIT** [comment] 2020-01-07 15:05
Strange that only osx has the problem.
I think the version of tensorflow that I use has protobuf requirement `>=3.6.1` for so I guess it may make sense that or-tools that requires version `>=3.10` crashes if the older version is loaded. (But it's strange that is does not load the installed version that is the 3.11.2.)

I'll use the import order workaround for now, and try again when 7.5 is out.

Thanks
