### ISSUE TITLE
How to oblige vehicle to not pass on a set of nodes continuously 

### ISSUE THREAD

**Issue by anis-coding** [google/or-tools#1281] opened 2019-05-16 00:58 UTC
Hey ortools gurus

Basically I would like to add a constraint which would not allow a vehicle pass on set of nodes continuously, for example let's say I have two sets of nodes, set A contains 4 nodes:  [1,2,3,4] and another set B contains 3 nodes [5,6,7]

My goal is to solve a standard vrp but with this additional constraint, in this example according to the constraint a vehicle can't go from 1->3 or 1-> 4 or from 3->2 ... etc directly because they are from the same set, however it can go indirectly : 1->6->4 for example or 3->7->4 and vice versa

So a vehicle can't go from a given to another node in the same set directly, it has to pass by some node from another set to be able to . 

Is there a way to do this through ortools or some workaround using penalties? 

Thank you

**Comment by lperron** [comment] 2019-05-16 06:15
Just tweak the distance between these nodes to forbid 1->3, 1->4...
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *Souames Annis <notifications@github.com>
*Date : *jeu. 16 mai 2019 à 02:58
*À : *google/or-tools
*Cc : *Subscribed

Hey ortools gurus

**Comment by Mizux** [comment] 2019-05-16 06:41
duplicate of #1123

**Closed by Mizux** 2019-05-16 06:41 UTC
Labels: Duplicate, Help Needed, Solver: Routing Solver
