### ISSUE TITLE
Support for ortools in Golang

### ISSUE THREAD

**Issue by supriya-clutter** [google/or-tools#953] opened 2018-11-29 21:58 UTC
Has there been any it interest to support the or tools API in Go ? 

EDIT:
Current implementation:
- https://github.com/kchan628/or-tools/tree/go-wrapper (unmaintained)
- https://github.com/gonzojive/or-tools-go
- https://github.com/keenanwl/or-tools/tree/add-go-wrapper
- https://github.com/AirspaceTechnologies/or-tools (go for routing ?)
- https://github.com/irfansharif/solver (CP-SAT go wrapper)

ToDo List:
* [ ] SWIG go wrapper
  * [ ] Linear solver go swig
  * [ ] Constraint Solver go swig
  * [ ] Sat go swig
  * [ ] Graph go swig
* [ ] Makefile support
* [ ] CMake support
* [ ] [optional] Bazel support
* [ ] Archive integration

**Comment by Mizux** [comment] 2018-11-30 07:01
It is currently not planned for he foreseeable future but since SWIG seems to support GO feel free to send us a PR for the support...

ref: http://www.swig.org/Doc3.0/SWIGDocumentation.html#Go

**Comment by kchan628** [comment] 2019-05-13 16:22
Hi, for anyone trying to go down this route. I started implementing a port of the java cp sat wrapper for go here. But we have decided to go java instead. For anyone that wants to complete the task you might want to pickup the work I started. I had branched from v7.0 tag. 

https://github.com/google/or-tools/compare/v7.0...kchan628:go-wrapper

See the makefiles/Makefile.go.mk as a starting point. It currently only supports Mac

```
make third_party
make go
make test_go
```

See wrapper code at /go/sat

**Comment by lperron** [comment] 2019-05-13 20:00
Hi,

very nice.
Can you change the CL such that generated go code is in ortools/gen/go/ or
ortools/gen/ortools/go
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *kchan628 <notifications@github.com>
*Date : *lun. 13 mai 2019 à 18:22
*À : *google/or-tools
*Cc : *Subscribed

Hi, for anyone trying to go down this route. I started implementing a port

**Comment by kchan628** [comment] 2019-05-13 20:37
hi @lperron I'm not planning to do any more dev work on the go wrapper at the moment. But that seems like a small change to make if somebody wants to continue it.

**Comment by lperron** [comment] 2019-08-06 20:23
Agreed. Unfortunately, I have no bandwidth to work on this.

**Comment by gonzojive** [comment] 2020-05-26 08:27
Would the OR tools authors like to include Go bindings in the official repo? I created a small project with SWIG bindings and a handwritten layer on top of the SWIG bindings here: https://github.com/gonzojive/or-tools-go.

The repo builds with Bazel, which was easier than dealing with `make` and friends for me. 

I would prefer to merge the project into the official repo so it can be tested continuously and not subject to as much bitrot, but of course it's up to the authors.

**Comment by Mizux** [comment] 2020-05-26 09:16
@gonzojive are you a Googler ?
note: we have fresh go wrapper (~Q1 2020 IIRC) in util/operations_research/linear_solver/go/ ...

**Comment by CosminNechifor** [comment] 2020-08-11 08:42
Out of curiosity: I see that this was added on the v7.8 milestone. Can you please leave a comment with a small update regarding the go wrapper or if it in your future plans? Thank you. (Decided not to open a feat request since it would be clearly a duplicate of this)

**Comment by keenanwl** [comment] 2020-09-22 19:29
I continued on where @kchan628 left off (thanks!):

[master...keenanwl:add-go-wrapper](https://github.com/google/or-tools/compare/master...keenanwl:add-go-wrapper)

I also converted some of the Java examples into go test files, like the [sudoku sat](https://github.com/keenanwl/or-tools/blob/add-go-wrapper/ortools/go/sat/cp_solver_test.go#L148)

In order to keep go.mod happy, I didn't move the generated files to `ortools/gen/ortools/go` as @lperron requested, but there may still be an idiomatic go way to get that done.

There is still some work needed to clean up a bit, fix the comments and add support for the knapsack solver, and any others I missed.

Otherwise:

```
make third_party
make go
make test_go
```

**Comment by lperron** [comment] 2020-09-22 20:04
Actually, is it possible to generate the files in
ortools/gen/ortools/sat/go (for the sat part) and still be able to import
as ortools.sat.go ?

This is very nice.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment] 2020-09-22 20:20
Added a list at top with forks having some go stuff..., hope to work on it once release 8.0 is out

**Comment by keenanwl** [comment] 2020-09-22 21:22
@lperron yes, that should be possible. I'll take a look at it tomorrow and see what I come up with.

**Comment by keenanwl** [comment] 2020-09-23 21:13
So I had to drop the `/go` child directory so as to avoid the generated protobuf packages all, undesirably, being named [go](https://developers.google.com/protocol-buffers/docs/reference/go-generated#package), but otherwise there are just a few more protobuf related path issues I need to update and then all the generated code will reside in `ortools/gen/ortools/sat`, etc.

**Comment by amirmm11** [comment] 2021-06-30 21:07
@Mizux Would it be easier to wrap the OR-Tools C++ code in a gRPC server (since protocol buffer files exist) and put it in a docker? Then everyone can pull the docker image and write a gRPC client.

**Comment by irfansharif** [comment] 2021-07-31 01:36
Here's a functioning subset of the CP-SAT solver in Go: https://github.com/irfansharif/or-tools. Built on top of @gonzojive + @brettgoing earlier work -- thanks!

**Comment by prasad-marne** [comment] 2021-09-16 03:27
@Mizux  Any updates on this? I am willing to put in work to add Golang support for constraint solver. 
Will it be alright to create a PR for that?

**Comment by solanu** [comment] 2021-09-23 06:37
What about this? ;-)

**Comment by Mizux** [comment] 2021-09-30 19:14
Hi sorry for the delay...
Hope to release v9.1 tomorrow then let's have a serious look at Golang support and how to move forward on this subject.

**Comment by piyushuber** [comment] 2022-01-17 12:38
Hi. Any updates on this one ?

**Comment by lperron** [comment] 2022-01-17 12:43
None, too busy.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 17 janv. 2022 à 13:38, piyushuber ***@***.***> a
écrit :

**Comment by cristaloleg** [comment] 2024-01-04 11:13
Hey, do you need any help with that?

**Comment by lperron** [comment] 2024-01-08 10:09
yes!!!

I pushed the CP-SAT go code and samples:
  - code in ortools/sat/go with 2 cgo files and some go files
  - samples in ortools/sat/samples/*go

It does not contain any build instruction. In particular, I do not know how
to package a go library that contains a significant C++ code.

Here is our badly exported BUILD file for reference in ortools/sat/go. Many
of the deps are wrong and should be fixed.

go_library(
name = "cpmodel",
srcs = [
"cp_model.go",
"cp_solver.go",
"domain.go",
],
cgo = 1,
deps = [
":cp_solver_c", # keep
"//base/go:log", # not present in OSS
"//third_party/golang/protobuf/v2/proto", # Wrong path
"//ortools/sat:cp_model_go_proto",
"//ortools/sat:sat_parameters_go_proto",
],
)

go_test(
name = "cpmodel_test",
srcs = [
"cp_model_test.go",
"cp_solver_test.go",
"domain_test.go",
],
cgo = 1,
library = ":cpmodel",
deps = [
"//base/go:log",
"//third_party/golang/cmp",
"//third_party/golang/protobuf/v2/proto", # Wrong path
"//third_party/golang/protobuf/v2/testing/protocmp", # Wrong path
"//ortools/sat:cp_model_go_proto",
"//ortools:sat_parameters_go_proto",
],
)

cc_library(
name = "cp_solver_c",
srcs = ["cp_solver_c.cc"],
hdrs = ["cp_solver_c.h"],
deps = [
"//strings",
"//third_party/absl/log",
"//ortools/sat:cp_model_cc_proto",
"//ortools/sat:cp_model_solver",
"//ortools/sat:sat_parameters_cc_proto",
"//ortools/util:time_limit",
"//util/task:status", # Should use absl status
"//util/task:status_cc_proto", # Does it exists in OSS ?
],
)

If you are familiar with cmake, you can use cmake.

Thanks
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 4 janv. 2024 à 12:13, Oleg Kovalov ***@***.***> a
écrit :

**Comment by Mizux** [comment] 2024-01-08 14:42
With color syntax:
```bzl
go_library(
name = "cpmodel",
srcs = [
"cp_model.go",
"cp_solver.go",
"domain.go",
],
cgo = 1,
deps = [
":cp_solver_c", # keep
"//base/go:log", # not present in OSS
"//third_party/golang/protobuf/v2/proto", # Wrong path
"//ortools/sat:cp_model_go_proto",
"//ortools/sat:sat_parameters_go_proto",
],
)

go_test(
name = "cpmodel_test",
srcs = [
"cp_model_test.go",
"cp_solver_test.go",
"domain_test.go",
],
cgo = 1,
library = ":cpmodel",
deps = [
"//base/go:log",
"//third_party/golang/cmp",
"//third_party/golang/protobuf/v2/proto", # Wrong path
"//third_party/golang/protobuf/v2/testing/protocmp", # Wrong path
"//ortools/sat:cp_model_go_proto",
"//ortools:sat_parameters_go_proto",
],
)

cc_library(
name = "cp_solver_c",
srcs = ["cp_solver_c.cc"],
hdrs = ["cp_solver_c.h"],
deps = [
"//strings",
"//third_party/absl/log",
"//ortools/sat:cp_model_cc_proto",
"//ortools/sat:cp_model_solver",
"//ortools/sat:sat_parameters_cc_proto",
"//ortools/util:time_limit",
"//util/task:status", # Should use absl status
"//util/task:status_cc_proto", # Does it exists in OSS ?
],
)
```

**Comment by luluz66** [comment] 2024-08-28 23:55
I made an attempt [here](https://github.com/google/or-tools/pull/4362) to update the dependencies and make it work with bazel. 
 And I can depend on this library in my [test repo](https://github.com/luluz66/solver-test) and run the go code.

**Comment by lperron** [comment] 2024-10-09 08:34
We have working go support in bazel. That is as far as we will go.

**Closed by lperron** 2024-10-09 08:34 UTC
Labels: Feature Request, Lang: Golang

**Comment by chaptersix** [comment] 2024-10-26 16:08
@lperron and @luluz66 It looks like the changes that @luluz66 referenced made it into the main branch but not the stable branch. I was able to set up my project using her fork. Any idea when bazel support will be in the stable branch/ in a release? I assume that's when I'll be able to use this repo directly.

**Comment by chaptersix** [comment] 2024-10-26 16:09
> [@lperron](https://github.com/lperron) and [@luluz66](https://github.com/luluz66) It looks like the changes that [@luluz66](https://github.com/luluz66) referenced made it into the main branch but not the stable branch. I was able to set up my project using her fork. Any idea when bazel support will be in the stable branch/ in a release? I assume that's when I'll be able to use this repo directly.

My bad, just noticed this got added to the v9.12 milestone.

**Comment by n-ozerov** [comment] 2024-12-21 22:43
could someone please share a simple example of cpsat with go? can't get it to work

**Comment by Mizux** [comment] 2024-12-23 08:58
/!\ Not tested nor endorsed so please read the source code /!\
According to https://github.com/google/or-tools/pull/4362 you may try to test her pet project: https://github.com/luluz66/solver-test

**Comment by vec715** [comment] 2025-09-04 01:20
so what is the latest status here? Golang is still unsupported?

**Comment by lperron** [comment] 2025-09-04 03:11
We have go support with CP-SAT with basel. 

I do not know how to package a go artifact with complex c++ dependencies.
