### ISSUE TITLE
Traffic factor in vehicle routing problems

### ISSUE THREAD

**Issue by rc-eddy** [google/or-tools#369] opened 2017-04-18 12:41 UTC
Is there a way to accommodate traffic in vehicle routing problems? That is to evaluate the transit time between two node indices as a function of index A, index B _and_ the accumulated time instead of just the indices?

**Comment by dkourilov** [comment] 2017-05-07 01:33
See RoutingModel::AddDimensionDependentDimensionWithVehicleCapacity (note, it's not exported in swig, so C++ only).

**Comment by Mizux** [comment] 2018-03-12 12:30
related to #480 #461 #339

**Comment by lperron** [comment] 2019-08-06 17:09
Duplicate of many issues.

The feature is experimental, and will not be wrapped by swig in the foreseable future.

**Closed by lperron** 2019-08-06 17:09 UTC
Labels: Duplicate, Help Needed, Lang: Python, Solver: Routing Solver
