### ISSUE TITLE
Slack definition is violated

### ISSUE THREAD

**Issue by KeremAslan** [google/or-tools#2205] opened 2020-10-22 08:59 UTC
**What version of OR-tools and what language are you using?**
Version: v7.7.7810
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
MacOS

**Bug description**
I have noticed a discrepancy between my models and the values returned by OR-Tools when validating the arrival times against my own models. I have simplified the problem down to 4 jobs which have the following slack, cumul and transit values (in sequence):

```
Node 74, slackMin 0, slackMax 784, slackVal 0, transitVal 120, cumulVal 1602630000, cumulMin 1602630000, cumulMax 1602630784 
Node 72, slackMin 0, slackMax 784, slackVal 0, transitVal 2566, cumulVal 1602630120, cumulMin 1602630120, cumulMax 1602630904 
Node 75, slackMin 0, slackMax 784, slackVal 0, transitVal 1930, cumulVal 1602632686, cumulMin 1602632686, cumulMax 1602633470 
Node 73, slackMin 0, slackMax 0, slackVal 0, transitVal 0, cumulVal 1602635400, cumulMin 1602635400, cumulMax 1602635400
```
By the definition of slack  `slack(i) = cumul(j) - cumul(i) - transit(i, j)`, I'd expect a `slackVal` of `784` at node `75` (`1602635400- 1602632686-1930=784`), but it seems OR-Tools is aware of this but doesn't set the slack value as expected on node `73`. The `slackVal` for the other nodes seem correct however. 
 
I believe this issue is related to this one: https://github.com/google/or-tools/issues/2101

Am I right in my observation?

**Comment by Mizux** [comment] 2020-10-23 07:17
does your route is `74 -> 72 -> 75 -> 73` ?
in this case you have `slack(75) = cumul(73) - cumul(75) - transit(75, 73)`

**Comment by KeremAslan** [comment] 2020-10-23 07:59
@Mizux yes. If you fill in the values in that formula you get `1602635400- 1602632686-1930=784`. Which does not match `slackMin` or `slackVal` which it outputs as `0`.

**Comment by Mizux** [comment] 2020-10-23 08:43
in the solution nextVar(i) should have a value i.e. you should have one next so transit(i) = transit(i,j) with j being the nextVar(i).value IIRC

**Comment by KeremAslan** [comment] 2020-10-23 09:52
OK, so `transit(75) = transit(75, 73) = 1930`. 
Then `slack(75) = cumul(73) - cumul(75) - transit(75)` => `784`, i.e. ` 784 = 1602635400- 1602632686-1930`. But when I do 
```
val slackDecisionVariableAtNode = timeDimension.slackVar(orToolsIndex)
val slackVal = assignment.Value(slackDecisionVariableAtNode) // returns 0
```
Isn't this violating the definition of slack?

**Comment by Mizux** [comment] 2020-10-23 10:06
As you write earlier, it gives you a Domain like for cumul since you have time windows.

see: https://github.com/google/or-tools/issues/1051#issuecomment-461033132

**Comment by KeremAslan** [comment] 2020-10-26 02:07
Sorry, I still don't think I understand why it is giving a range. Let me add that I have added  `addVariableMinimizedByFinalizer()` to my model, so the model should pick the earliest departure possibility. Hence, the slack value at each node should be

- Node 74: 0
- Node 72: 0
- Node 75: 784
- Node 73: 0

Is it giving a range at the first three nodes because it doesn't matter where that slack is utilized?

**Comment by Mizux** [comment] 2020-10-26 08:39
IIRC, your route is `74 -> 72 -> 75 -> 73`.
Even when you minimize the time at end (`73`), you'll have to wait 784 along the road. which can be at one node or `784/3` at each nodes (`74`, `72` and `75`).
All this solutions are equivalents for the solver (i.e. same objective value) so instead of choosing one, the solver return the merge of all of them.

**Comment by KeremAslan** [comment] 2020-10-28 06:31
Yes, I have used `addVariableMinimizedByFinalizer()` for all nodes. 

So, OR-Tools doesn't pick the slack value if it doesn't matter where it is applied? Even though it clearly violates the defintion of slack?

**Comment by Mizux** [comment] 2021-03-22 15:19
I would say the routing solver, by design, will always return a bunch of interleaved solutions having the same objective value when using slacks.

I'll close this issue since no one is or will work on changing this "behaviour".

**Closed by Mizux** 2021-03-22 15:19 UTC
Labels: Duplicate, Help Needed, Solver: Routing Solver
