### ISSUE TITLE
Multiple trips

### ISSUE THREAD

**Issue by yuranov** [google/or-tools#1176] opened 2019-04-07 11:27 UTC
Is there a working solution to solve problem with multiple trips?
Trip can contains pickups and deliveries.
I found examples with reload and refueling, but seems it's not working properly for this case.

**Comment by Mizux** [comment] 2019-04-08 06:55
What do you mean by not working properly, do you have simple sample not working so we can reproduce it ?

**Comment by Skyien** [comment] 2019-04-08 09:17
@Mizux  I already deleted, but tried to do it again. 
I understand correctly that or-tools can that solve this problem?

**Comment by lperron** [comment] 2019-08-06 20:17
Duplicate of #976

**Closed by lperron** 2019-08-06 20:17 UTC
Labels: Help Needed, Solver: Routing Solver
