### ISSUE TITLE
constraint-solver.pywrapcp loads 10+ minutes

### ISSUE THREAD

**Issue by replicantdeca** [google/or-tools#1154] opened 2019-03-26 06:34 UTC
I get this error in my console:
```shell
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0326 12:46:35.182485 1528 expr_array.cc:3329] operations_research::Solver::MakeMax() was called with an empty list of variables. Was this intentional?
```
and I used to be able to make the Solver render results but it took longer and longer. Now it takes so long that one I ran minutes ago is still at it right now. What seems to be the problem here?

**Comment by Mizux** [comment] 2019-03-26 07:29
Which version of ortools did you use ?
do you have a code snippet, so we can reproduce it ?

**Comment by replicantdeca** [comment] 2019-03-26 07:37
**VERSION**:
Requirement already satisfied: ortools in c:\users\decqua\appdata\roaming\python\python36\site-packages (6.9.5824)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\decqua\appdata\local\programs\python\python36\lib\site-packages (from ortools) (3.6.1)
Requirement already satisfied: six>=1.10 in c:\users\decqua\appdata\local\programs\python\python36\lib\site-packages (from ortools) (1.11.0)
Requirement already satisfied: setuptools in c:\users\decqua\appdata\local\programs\python\python36\lib\site-packages (from protobuf>=3.6.1->ortools) (40.5.0)

**CODE**:
horizon = 0
    for i in all_jobs:
        horizon += sum(processing_times[i])
        horizon = int(horizon)

    # Create jobs.
    all_tasks = {}
    for i in all_jobs:
        for j in range(0, len(machines[i])):
            all_tasks[(i, j)] = solver.FixedDurationIntervalVar(0,
                                                                horizon,
                                                                processing_times[i][j],
                                                                False,
                                                                'Job_%i_%i' % (i, j))
    print('defined all_tasks')
    print(all_tasks)

    # Create sequence variables and add disjunctive constraints.
    all_sequences = []
    for i in all_machines:
        machines_jobs = []
        for j in all_jobs:
            for k in range(0, len(machines[j])):
                if machines[j][k] == i:
                    machines_jobs.append(all_tasks[(j, k)])
        disj = solver.DisjunctiveConstraint(machines_jobs, 'machine %i' % i)
        all_sequences.append(disj.SequenceVar())
        solver.Add(disj)
    print('defined all_sequences')
    print(all_sequences)

    # Add conjunctive constraints.
    for i in all_jobs:
        for j in range(0, len(machines[i]) - 1):
            solver.Add(all_tasks[(i, j + 1)].StartsAfterEnd(all_tasks[(i, j)]))

    print('defined conjunctive constraints')
    print(solver)
    # TODO Consider date_required of job
    '''
    for job in all_jobs:
        for task_id in range(0, len(jobs_count) - 1):
            solver.Add(all_tasks[job, task_id +
                                1].start >= all_tasks[job, task_id].end)
    '''

    # Set the objective.
    obj_var = solver.Max([all_tasks[(i, len(machines[i]) - 1)].EndExpr()
                          for i in all_jobs])
    objective_monitor = solver.Minimize(obj_var, 1)
    # Create search phases.
    sequence_phase = solver.Phase([all_sequences[i] for i in all_machines],
                                  solver.SEQUENCE_DEFAULT)
    vars_phase = solver.Phase([obj_var],
                              solver.CHOOSE_FIRST_UNBOUND,
                              solver.ASSIGN_MIN_VALUE)
    main_phase = solver.Compose([sequence_phase, vars_phase])
    # Create the solution collector.
    collector = solver.LastSolutionCollector()

    # Add the interesting variables to the SolutionCollector.
    collector.Add(all_sequences)
    collector.AddObjective(obj_var)
    print('defined objective')
    print(obj_var)

    print('defined collector')
    print(collector)


    for i in all_machines:
        sequence = all_sequences[i];
        sequence_count = sequence.Size();
        for j in range(0, sequence_count):
            t = sequence.Interval(j)
            collector.Add(t.StartExpr().Var())
            collector.Add(t.EndExpr().Var())

    # Solve the problem.
    # Arrays for plotly gantt chart
    plot_list = []
    machine_list = []
    start_list = []
    finish_list = []
    resource_list = []
    description_list = []
    current_time = np.datetime64(datetime.datetime.now())

    if solver.Solve(main_phase, [objective_monitor, collector]):
        for i in all_machines:
            seq = all_sequences[i]
            machine_list.append(get_machine_type(i))  # Add machine name
            sequence = collector.ForwardSequence(0, seq)
            seq_size = len(sequence)

            for j in range(0, seq_size):
                t = seq.Interval(sequence[j]);
                temp_name = t.Name().split('_')  # , 1)[1]
                temp_name_test = temp_name
                temp_name = temp_name[1]  # get the job number
                job_num = int(temp_name)
                resource_list.append(str(df.ix[job_num, 'id']))  # Add resource (aka Job ID)
                description_list.append(df.ix[job_num, 'material_type'])  # Add material used to description list

            for j in range(0, seq_size):
                t = seq.Interval(sequence[j]);
                # Add start time
                start_list.append(get_start_time(current_time, collector.Value(0, t.StartExpr().Var())))
                # Add finish time
                finish_list.append(get_finish_time(current_time, collector.Value(0, t.EndExpr().Var())))

            for j in range(0, seq_size):
                temp_dict = {'Task': machine_list[i],
                             'Start': start_list.pop(0),
                             'Finish': finish_list.pop(0),
                             'Resource': resource_list.pop(0),
                             'Description': description_list.pop(0),
                             }
                plot_list.append(temp_dict)

**Comment by replicantdeca** [comment] 2019-03-26 07:39
As for it taking longer and longer. The other day, loading time was only a few minutes. before that, running the method didn't take that long and didn't generate that error/warning from the original post. Earlier, it was up to 15+ minutes and sometimes it would crash.

**Comment by lperron** [comment] 2019-03-26 08:11
Can you also provide the date, we cannot run the code as it is.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 26 mars 2019 à 08:39, replicantdeca <notifications@github.com> a
écrit :

**Comment by replicantdeca** [comment] 2019-03-26 08:13
What date? I can send the actual method of the code..

**Comment by replicantdeca** [comment] 2019-03-26 08:17
# Solves the job shop problem using OR-tools constraint solver, returns a dictionary with the solution
def schedule(df, filename):
    solver = pywrapcp.Solver('jobshop')

    machines_count = Machine.objects.filter(state='OK').count() # Extrude, Print, (Laminate), Cut
    machine_type = Machine.objects.filter(state='OK')
    workers_count = Employee.objects.filter(Q(position='Cutting') | Q(position='Extruder') | Q(position='Printing') | Q(position='Laminating')).count()
    jobs_count = len(df.index)
    all_machines = range(0, machines_count)
    all_jobs = range(0, jobs_count)

    # Define data.
    machines = []
    for i in range(0, len(df.index)):
        # Include Printing and Laminating machine
        if df.ix[i]['printed'] == 1 and df.ix[i]['laminate'] == 1:
            machines.append([0, 1, 2, 3])
        # Include only Printing
        elif df.ix[i]['printed'] == 1:
            machines.append([0, 1, 3])
        # Include only Laminating
        elif df.ix[i]['laminate'] == 1:
            machines.append([0, 2, 3])
        else:
            machines.append([0, 3])
    print('defined data')
    print(machines)

    processing_times = []
    for i in range(0, len(df.index)):
        # Include Printing and Laminating machine
        # Standard lead time: Plain - 1-2 weeks; Printed - 2-4 weeks
        # IN HOURS:
        # Extruder = 4 days * 20 hours every 70000 pieces = 80hr/70000pcs
        # Cutting = 3 days * 20 hours every 70000 pieces = 60hr/70000pcs
        # Laminating = 3 days * 20 hours every 70000 pieces = 60hr/70000pcs
        # Printing = 5 days * 20 hours  every 70000 pieces = 100hr/70000pcs
        item = ClientItem.objects.get(client_po_id=df.ix[i]['id'])
        quantity = item.quantity
        extrusion_time = int((quantity * 80) / 70000)
        cutting_time = int((quantity * 60) / 70000)
        laminating_time = int((quantity * 60) / 70000)
        printing_time = int((quantity * 100) / 70000)

        if df.ix[i]['printed'] == 1 and df.ix[i]['laminate'] == 1:
            processing_times.append(
                [extrusion_time, printing_time, laminating_time, cutting_time])  # Extrude, Print, Laminate, Cut
        # Include only Printing
        elif df.ix[i]['printed'] == 1:
            processing_times.append([extrusion_time, printing_time, cutting_time])
        # Include only Laminating
        elif df.ix[i]['laminate'] == 1:
            processing_times.append([extrusion_time, laminating_time, cutting_time])
        else:
            processing_times.append([extrusion_time, cutting_time])

    print('defined processing times')
    print(processing_times)

    # Compute horizon.
    horizon = 0
    for i in all_jobs:
        horizon += sum(processing_times[i])
        horizon = int(horizon)

    # Create jobs.
    all_tasks = {}
    for i in all_jobs:
        for j in range(0, len(machines[i])):
            all_tasks[(i, j)] = solver.FixedDurationIntervalVar(0,
                                                                horizon,
                                                                processing_times[i][j],
                                                                False,
                                                                'Job_%i_%i' % (i, j))
    print('defined all_tasks')
    print(all_tasks)

    # Create sequence variables and add disjunctive constraints.
    all_sequences = []
    for i in all_machines:
        machines_jobs = []
        for j in all_jobs:
            for k in range(0, len(machines[j])):
                if machines[j][k] == i:
                    machines_jobs.append(all_tasks[(j, k)])
        disj = solver.DisjunctiveConstraint(machines_jobs, 'machine %i' % i)
        all_sequences.append(disj.SequenceVar())
        solver.Add(disj)
    print('defined all_sequences')
    print(all_sequences)

    # Add conjunctive constraints.
    for i in all_jobs:
        for j in range(0, len(machines[i]) - 1):
            solver.Add(all_tasks[(i, j + 1)].StartsAfterEnd(all_tasks[(i, j)]))

    print('defined conjunctive constraints')
    print(solver)
    # TODO Consider date_required of job
    '''
    for job in all_jobs:
        for task_id in range(0, len(jobs_count) - 1):
            solver.Add(all_tasks[job, task_id +
                                1].start >= all_tasks[job, task_id].end)
    '''

    # Set the objective.
    obj_var = solver.Max([all_tasks[(i, len(machines[i]) - 1)].EndExpr()
                          for i in all_jobs])
    objective_monitor = solver.Minimize(obj_var, 1)
    # Create search phases.
    sequence_phase = solver.Phase([all_sequences[i] for i in all_machines],
                                  solver.SEQUENCE_DEFAULT)
    vars_phase = solver.Phase([obj_var],
                              solver.CHOOSE_FIRST_UNBOUND,
                              solver.ASSIGN_MIN_VALUE)
    main_phase = solver.Compose([sequence_phase, vars_phase])
    # Create the solution collector.
    collector = solver.LastSolutionCollector()

    # Add the interesting variables to the SolutionCollector.
    collector.Add(all_sequences)
    collector.AddObjective(obj_var)
    print('defined objective')
    print(obj_var)

    print('defined collector')
    print(collector)

    for i in all_machines:
        sequence = all_sequences[i];
        sequence_count = sequence.Size();
        for j in range(0, sequence_count):
            t = sequence.Interval(j)
            collector.Add(t.StartExpr().Var())
            collector.Add(t.EndExpr().Var())

    # Solve the problem.
    # Arrays for plotly gantt chart
    plot_list = []
    machine_list = []
    start_list = []
    finish_list = []
    resource_list = []
    description_list = []
    current_time = np.datetime64(datetime.datetime.now())

    if solver.Solve(main_phase, [objective_monitor, collector]):
        for i in all_machines:
            seq = all_sequences[i]
            machine_list.append(get_machine_type(i))  # Add machine name
            sequence = collector.ForwardSequence(0, seq)
            seq_size = len(sequence)

            for j in range(0, seq_size):
                t = seq.Interval(sequence[j]);
                temp_name = t.Name().split('_')  # , 1)[1]
                temp_name_test = temp_name
                temp_name = temp_name[1]  # get the job number
                job_num = int(temp_name)
                resource_list.append(str(df.ix[job_num, 'id']))  # Add resource (aka Job ID)
                description_list.append(df.ix[job_num, 'material_type'])  # Add material used to description list

            for j in range(0, seq_size):
                t = seq.Interval(sequence[j]);
                # Add start time
                start_list.append(get_start_time(current_time, collector.Value(0, t.StartExpr().Var())))
                # Add finish time
                finish_list.append(get_finish_time(current_time, collector.Value(0, t.EndExpr().Var())))

            # TODO Include worker in schedule
            '''
                        for j in range(0, seq_size):
                            #t = seq.Interval(sequence[j]);
                            worker_list.append(get_worker(j))
            '''

            for j in range(0, seq_size):
                temp_dict = {'Task': machine_list[i],
                             'Start': start_list.pop(0),
                             'Finish': finish_list.pop(0),
                             'Resource': resource_list.pop(0),
                             'Description': description_list.pop(0),
                             }
                plot_list.append(temp_dict)

        print('sched() plot_list:')
        print(plot_list)

        if filename == 'specific':
            return plot_list

        elif filename == 'save':
            return plot_list

        else:
            # print(plot_list)
            return chart(plot_list, filename)

**Comment by lperron** [comment] 2019-03-26 08:18
data, sorry
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 26 mars 2019 à 09:13, replicantdeca <notifications@github.com> a
écrit :

**Comment by lperron** [comment] 2019-03-26 08:20
Anyway, you should use the CP-SAT solver.

You can have a look at
https://github.com/google/or-tools/blob/stable/examples/python/jobshop_ft06_sat.py

which is very close from your problem (apart from the data of course)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by replicantdeca** [comment] 2019-03-26 08:22
plot_list = 

[{'Task': 'Extruder', 'Start': '2019-03-25 09:21:00+00:00', 'Finish': '2019-03-25 20:21:00+00:00', 'Resource': 26, 'Description': 'LDPE'}, {'Task': 'Extruder', 'Start': '2019-03-26 20:34:00+00:00', 'Finish': '2019-03-27 07:34:00+00:00', 'Resource': 22, 'Description': 'HDPE'}, {'Task': 'Extruder', 'Start': '2019-03-27 07:34:00+00:00', 'Finish': '2019-03-27 18:34:00+00:00', 'Resource': 27, 'Description': 'LDPE'}, {'Task': 'Extruder', 'Start': '2019-03-28 16:34:00+00:00', 'Finish': '2019-03-29 03:34:00+00:00', 'Resource': 29, 'Description': 'LLDPE'}, {'Task': 'Extruder', 'Start': '2019-03-29 16:46:00+00:00', 'Finish': '2019-03-30 05:46:00+00:00', 'Resource': 32, 'Description': 'HDPE'}, {'Task': 'Extruder', 'Start': '2019-03-26 15:09:00+00:00', 'Finish': '2019-03-27 17:09:00+00:00', 'Resource': 12, 'Description': 'HDPE'}, {'Task': 'Extruder', 'Start': '2019-03-27 17:09:00+00:00', 'Finish': '2019-03-28 21:09:00+00:00', 'Resource': 17, 'Description': 'PP'}, {'Task': 'Extruder', 'Start': '2019-03-28 21:09:00+00:00', 'Finish': '2019-03-29 09:09:00+00:00', 'Resource': 30, 'Description': 'HDPE'}, {'Task': 'Extruder', 'Start': '2019-03-29 09:09:00+00:00', 'Finish': '2019-03-30 13:09:00+00:00', 'Resource': 33, 'Description': 'PP'}, {'Task': 'Extruder', 'Start': '2019-03-30 13:09:00+00:00', 'Finish': '2019-03-31 06:09:00+00:00', 'Resource': 7, 'Description': 'HDPE'}, {'Task': 'Extruder', 'Start': '2019-03-31 06:09:00+00:00', 'Finish': '2019-04-01 08:09:00+00:00', 'Resource': 13, 'Description': 'LLDPE'}, {'Task': 'Extruder', 'Start': '2019-04-01 08:09:00+00:00', 'Finish': '2019-04-01 19:09:00+00:00', 'Resource': 8, 'Description': 'LDPE'}, {'Task': 'Extruder', 'Start': '2019-04-01 19:09:00+00:00', 'Finish': '2019-04-02 08:09:00+00:00', 'Resource': 34, 'Description': 'LDPE'}, {'Task': 'Extruder', 'Start': '2019-04-02 08:09:00+00:00', 'Finish': '2019-04-03 12:09:00+00:00', 'Resource': 23, 'Description': 'PP'}, {'Task': 'Extruder', 'Start': '2019-04-03 12:09:00+00:00', 'Finish': '2019-04-04 10:09:00+00:00', 'Resource': 9, 'Description': 'HDPE'}, {'Task': 'Extruder', 'Start': '2019-04-04 10:09:00+00:00', 'Finish': '2019-04-04 21:09:00+00:00', 'Resource': 21, 'Description': 'LDPE'}, {'Task': 'Extruder', 'Start': '2019-04-04 21:09:00+00:00', 'Finish': '2019-04-05 08:09:00+00:00', 'Resource': 28, 'Description': 'LDPE'}, {'Task': 'Extruder', 'Start': '2019-04-05 08:09:00+00:00', 'Finish': '2019-04-05 19:09:00+00:00', 'Resource': 24, 'Description': 'PP'}, {'Task': 'Cutting', 'Start': '2019-03-26 04:21:00+00:00', 'Finish': '2019-03-26 12:21:00+00:00', 'Resource': 26, 'Description': 'LDPE'}, {'Task': 'Cutting', 'Start': '2019-03-27 19:34:00+00:00', 'Finish': '2019-03-28 03:34:00+00:00', 'Resource': 27, 'Description': 'LDPE'}, {'Task': 'Cutting', 'Start': '2019-03-28 03:34:00+00:00', 'Finish': '2019-03-28 11:34:00+00:00', 'Resource': 22, 'Description': 'HDPE'}, {'Task': 'Cutting', 'Start': '2019-03-29 03:34:00+00:00', 'Finish': '2019-03-29 11:34:00+00:00', 'Resource': 29, 'Description': 'LLDPE'}, {'Task': 'Cutting', 'Start': '2019-03-30 05:46:00+00:00', 'Finish': '2019-03-30 15:46:00+00:00', 'Resource': 32, 'Description': 'HDPE'}, {'Task': 'Cutting', 'Start': '2019-03-29 09:09:00+00:00', 'Finish': '2019-03-29 18:09:00+00:00', 'Resource': 30, 'Description': 'HDPE'}, {'Task': 'Cutting', 'Start': '2019-03-29 22:09:00+00:00', 'Finish': '2019-03-30 18:09:00+00:00', 'Resource': 12, 'Description': 'HDPE'}, {'Task': 'Cutting', 'Start': '2019-03-30 18:09:00+00:00', 'Finish': '2019-03-31 15:09:00+00:00', 'Resource': 17, 'Description': 'PP'}, {'Task': 'Cutting', 'Start': '2019-03-31 15:09:00+00:00', 'Finish': '2019-04-01 03:09:00+00:00', 'Resource': 7, 'Description': 'HDPE'}, {'Task': 'Cutting', 'Start': '2019-04-01 03:09:00+00:00', 'Finish': '2019-04-02 00:09:00+00:00', 'Resource': 33, 'Description': 'PP'}, {'Task': 'Cutting', 'Start': '2019-04-02 00:09:00+00:00', 'Finish': '2019-04-02 08:09:00+00:00', 'Resource': 8, 'Description': 'LDPE'}, {'Task': 'Cutting', 'Start': '2019-04-02 08:09:00+00:00', 'Finish': '2019-04-02 18:09:00+00:00', 'Resource': 34, 'Description': 'LDPE'}, {'Task': 'Cutting', 'Start': '2019-04-02 18:09:00+00:00', 'Finish': '2019-04-03 13:09:00+00:00', 'Resource': 13, 'Description': 'LLDPE'}, {'Task': 'Cutting', 'Start': '2019-04-03 13:09:00+00:00', 'Finish': '2019-04-04 10:09:00+00:00', 'Resource': 23, 'Description': 'PP'}, {'Task': 'Cutting', 'Start': '2019-04-04 10:09:00+00:00', 'Finish': '2019-04-05 03:09:00+00:00', 'Resource': 9, 'Description': 'HDPE'}, {'Task': 'Cutting', 'Start': '2019-04-05 03:09:00+00:00', 'Finish': '2019-04-05 11:09:00+00:00', 'Resource': 21, 'Description': 'LDPE'}, {'Task': 'Cutting', 'Start': '2019-04-05 11:09:00+00:00', 'Finish': '2019-04-05 19:09:00+00:00', 'Resource': 28, 'Description': 'LDPE'}, {'Task': 'Cutting', 'Start': '2019-04-05 19:09:00+00:00', 'Finish': '2019-04-06 03:09:00+00:00', 'Resource': 24, 'Description': 'PP'}, {'Task': 'Printing', 'Start': '2019-03-27 07:34:00+00:00', 'Finish': '2019-03-27 21:34:00+00:00', 'Resource': 22, 'Description': 'HDPE'}, {'Task': 'Printing', 'Start': '2019-03-27 17:09:00+00:00', 'Finish': '2019-03-29 02:09:00+00:00', 'Resource': 12, 'Description': 'HDPE'}, {'Task': 'Printing', 'Start': '2019-03-29 02:09:00+00:00', 'Finish': '2019-03-30 13:09:00+00:00', 'Resource': 17, 'Description': 'PP'}, {'Task': 'Printing', 'Start': '2019-03-30 13:09:00+00:00', 'Finish': '2019-04-01 00:09:00+00:00', 'Resource': 33, 'Description': 'PP'}, {'Task': 'Printing', 'Start': '2019-04-01 08:09:00+00:00', 'Finish': '2019-04-02 17:09:00+00:00', 'Resource': 13, 'Description': 'LLDPE'}, {'Task': 'Laminating', 'Start': '2019-03-29 02:09:00+00:00', 'Finish': '2019-03-29 22:09:00+00:00', 'Resource': 12, 'Description': 'HDPE'}]

**Comment by replicantdeca** [comment] 2019-03-26 08:23
Would very much appreciate it if there would be a workaround for the current code. A deadline is coming up and everything was fine until this morning when the Solving would take 15+ minutes. :/ Thank you soooo much.

**Comment by replicantdeca** [comment] 2019-03-26 08:25
@Mizux @lperron it takes long at this part:

`if solver.Solve(main_phase, [objective_monitor, collector]):`

Tried invalidating my system cache already, transferring it to a new project. It still loads very slow. It used to load just fine. I'm not sure what else to do.

**Comment by lperron** [comment] 2019-03-26 08:31
Exactly why you should change.
I ported your code except the data part, and the solution printing part in
5 minutes.
The printing part is mostly done (sorting of sequences) here:
https://github.com/google/or-tools/blob/stable/ortools/sat/samples/minimal_jobshop_sat.py

from ortools.sat.python import cp_model

model = cp_model.CpModel()

horizon = 0
for i in all_jobs:
horizon += sum(processing_times[i])
horizon = int(horizon)

task_type = collections.namedtuple('task_type', 'start end interval')


# Create jobs.
all_tasks = {}
for i in all_jobs:
    for j in range(0, len(machines[i])):
        start_var = model.NewIntVar(0, horizon, 'start_%i_%i' % (i, j))
        duration = processing_times[i][j]
        end_var = model.NewIntVar(0, horizon, 'end_%i_%i' % (i, j))
        interval_var = model.NewIntervalVar(start_var, duration, end_var,
                                            'Job_%i_%i' % (i, j))
        all_tasks[(i, j)] = task_type(
            start=start_var, end=end_var, interval=interval_var)

print('defined all_tasks')

# Create sequence variables and add disjunctive constraints.
all_sequences = []
for i in all_machines:
    machines_jobs = []
    for j in all_jobs:
        for k in range(0, len(machines[j])):
            if machines[j][k] == i:
                machines_jobs.append(all_tasks[(j, k)].interval)
    model.AddNoOverlap(machine_jobs)
print('defined all_sequences')

# Add conjunctive constraints.
for i in all_jobs:
    for j in range(0, len(machines[i]) - 1):
        model.Add(all_tasks[(i, j + 1)].start >= all_tasks[(i, j)].end)

print('defined conjunctive constraints')
# TODO Consider date_required of job
'''
for job in all_jobs:
    for task_id in range(0, len(jobs_count) - 1):
        solver.Add(all_tasks[job, task_id +
                            1].start >= all_tasks[job, task_id].end)
'''

# Set the objective.
obj_var = model.NewIntVar(0, horizon, 'makespan')
model.AddMaxEquality(
    obj_var, [all_tasks[(i, machines_count - 1)].end for i in all_jobs])
model.Minimize(obj_var)

# Solve the problem.
solver = cp_model.CpSolver()
status = solver.Solve(model)


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 26 mars 2019 à 09:25, replicantdeca <notifications@github.com> a
écrit :

**Comment by replicantdeca** [comment] 2019-03-26 08:37
@lperron What is `collections`?

**Comment by replicantdeca** [comment] 2019-03-26 08:43
@lperron Thanks for this. However, I run into an error I really don't understand. I'm sorry I'm really new to Python :( 
![Screenshot (1035)](https://user-images.githubusercontent.com/33694143/54982621-2bf41680-4fe6-11e9-9ba9-d5e3d1899639.png)
![Screenshot (1036)](https://user-images.githubusercontent.com/33694143/54982623-2bf41680-4fe6-11e9-8de4-bc506af8ad2c.png)
![Screenshot (1037)](https://user-images.githubusercontent.com/33694143/54982624-2c8cad00-4fe6-11e9-901c-7f915e965c2b.png)

**Comment by lperron** [comment] 2019-03-26 08:43
a python module

Missed the first two lines

from __future__ import print_function

import collections

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 26 mars 2019 à 09:37, replicantdeca <notifications@github.com> a
écrit :

**Comment by lperron** [comment] 2019-03-26 08:46
I cannot reproduce

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 26 mars 2019 à 09:43, replicantdeca <notifications@github.com> a
écrit :

**Comment by replicantdeca** [comment] 2019-03-26 09:22
@lperron Is it possible to have a workaround instead with my current def schedule()? Like is there anything I can just change within that method rather than changing the entire model?

**Comment by lperron** [comment] 2019-03-26 09:27
I do not think so.
You are solving a NP-Hard problem, if your data change, if your problem
becomes bigger, it is normal that search (which is exponential) takes more
time.

In that regard, the CP-SAT is much more efficient.

Now, about the various bugs.
The empty max means there are no jobs in your problem as the max is used to
compute the makespan. Either the problem is empty, of there is some issues
with the code.

About the missing key, most likely, you have jobs with different numbers of
tasks. Somewhere in the code, it assumes num_tasks == num_machines.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 26 mars 2019 à 10:22, replicantdeca <notifications@github.com> a
écrit :

**Comment by lperron** [comment] 2019-04-16 15:36
Nothing new, closing the issue now.

**Closed** 2019-04-16 15:36 UTC
Labels: Help Needed, Lang: Python, Solver: CP / CP-SAT Solver
