### ISSUE TITLE
Add numpy support

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#2390] opened 2021-02-11 08:56 UTC
Numpy seems to already provide some python3 SWIG wrapper [`numpy.i`](https://github.com/numpy/numpy/blob/master/tools/swig/numpy.i)
ref: https://github.com/numpy/numpy/tree/master/tools/swig

We should try to see if we can support vector and matrix numpy types in our API directly...

Note(2022-02-20): we should switch as much as possible from swig python to pybind11, then add support for numpy in the graph/algorithms solvers.

**Comment by Mizux** [comment] 2022-05-02 13:01
FYI pybind11 has builtin numpy support https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html
So it can be wise to 1) migrate from SWIG to pybind11  2) add numpy support wherever it makes sense...

**Comment by lperron** [comment] 2022-11-22 10:54
Duplicate of https://github.com/google/or-tools/issues/1020

**Closed by lperron** 2022-11-22 10:54 UTC
Labels: Feature Request, Lang: Python
