### ISSUE TITLE
Documentation on Getting started with C++ is wrong/outdated.

### ISSUE THREAD

**Issue by krishvk** [google/or-tools#3723] opened 2023-03-29 12:09 UTC
**What version of OR-Tools and what language are you using?**
Version: or-tools_x86_64_Ubuntu-22.04_cpp_v9.6.2534
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu-22.04

**What did you do?**
1. Downloaded and extracted the or-tools for Ubuntu 22.04 LTS from https://developers.google.com/optimization/install/cpp/binary_linux
2. Saved the example from https://developers.google.com/optimization/introduction/cpp into a file `../program.cc`
3. Ran `make run SOURCE=../program.cc` as said on the above page
4. Error message: `make: *** No rule to make target 'examples/program/CMakeLists.txt', needed by 'build'.  Stop.`

Tried creating a CMakeList.txt file beside the program.cc

```
> mkdir ../program
> mv ../program.cc ../program
> cp examples/knapsack/CMakeLists.txt ../program
> sed -i 's#knapsack#program#g' ../program/CMakeLists.txt
> make run SOURCE=../program/program.cc
```

Still the same error

`make: *** No rule to make target 'examples/program/CMakeLists.txt', needed by 'build'.  Stop.`

Moved the directory to the examples directory and ran it again and it worked now

```
mv ../program examples
make run SOURCE=examples/program/program.cc
```

I think 

1. The documentation should be updated
2. The flow should be simpler as before. Should be possible to run remotely 

Please do let me know if I am missing anything

**Comment by lperron** [comment] 2023-03-30 06:48
Duplicate of #3558

**Closed by lperron** 2023-03-30 06:48 UTC
