### ISSUE TITLE
Benchmarking LAP

### ISSUE THREAD

**Issue by cheind** [google/or-tools#577] opened 2018-02-10 18:24 UTC
Hi,

I've been benchmarking various LAP solvers in Python here

https://github.com/cheind/py-lapsolver/tree/develop#benchmarks

As you can see, the results `ortools` are suboptimal. One reason, I figured, might be that this is due to the exposed Python API that requires calling `AddArcWithCost` for every cost matrix entry. Especially for dense matrices that eats up a lot of time. The `ortools` specific code can be found here

https://github.com/cheind/py-lapsolver/blob/develop/lapsolver/benchmarks/test_benchmark_solvers.py

In case you know a better way or spot an issue with my code, I'd be happy to hear from you.

**Comment by lperron** [comment] 2018-09-01 06:30
Duplicate of #321

**Closed by lperron** 2018-09-01 06:30 UTC
Labels: Help Needed
