### ISSUE TITLE
Ubuntu 16.04, Python 3.5 install failed with "wrong ELF class: ELFCLASS64"

### ISSUE THREAD

**Issue by PetrochukM** [google/or-tools#310] opened 2017-01-26 20:41 UTC
May I get some help?

I attempted to follow the instructions online to install or-tools on my DigitalOcean server. The library has worked well on my Macbook. But I am unable to install it on my Ubuntu server.

Distribution version
```
petrochuk@wardrobe:/var/www/wardrobe.tips$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

Python Version
```
$ python3 -V
Python 3.5.2
```

Setup.py
```
$ sudo /usr/bin/python3 setup.py install --user
running install
running bdist_egg
running egg_info
writing ortools_examples.egg-info/PKG-INFO
writing dependency_links to ortools_examples.egg-info/dependency_links.txt
writing requirements to ortools_examples.egg-info/requires.txt
writing top-level names to ortools_examples.egg-info/top_level.txt
reading manifest file 'ortools_examples.egg-info/SOURCES.txt'
writing manifest file 'ortools_examples.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/EGG-INFO
copying ortools_examples.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying ortools_examples.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying ortools_examples.egg-info/dependency_links.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying ortools_examples.egg-info/requires.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying ortools_examples.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ortools_examples-5.0.3919-py3.5.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing ortools_examples-5.0.3919-py3.5.egg
Removing /home/petrochuk/.local/lib/python3.5/site-packages/ortools_examples-5.0.3919-py3.5.egg
Copying ortools_examples-5.0.3919-py3.5.egg to /home/petrochuk/.local/lib/python3.5/site-packages
ortools-examples 5.0.3919 is already the active version in easy-install.pth

Installed /home/petrochuk/.local/lib/python3.5/site-packages/ortools_examples-5.0.3919-py3.5.egg
Processing dependencies for ortools-examples==5.0.3919
Searching for py3-ortools==5.1.4041
Best match: py3-ortools 5.1.4041
Processing py3_ortools-5.1.4041-py3.5-linux-i686.egg
py3-ortools 5.1.4041 is already the active version in easy-install.pth

Using /home/petrochuk/.local/lib/python3.5/site-packages/py3_ortools-5.1.4041-py3.5-linux-i686.egg
Searching for protobuf==3.0.0
Best match: protobuf 3.0.0
protobuf 3.0.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages
Searching for setuptools==20.7.0
Best match: setuptools 20.7.0
setuptools 20.7.0 is already the active version in easy-install.pth
Installing easy_install script to /home/petrochuk/.local/bin

Using /usr/lib/python3/dist-packages
Searching for six==1.10.0
Best match: six 1.10.0
six 1.10.0 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Finished processing dependencies for ortools-examples==5.0.3919
```

Check Python Deps
```
$ python3 check_python_deps.py
INFO:root:Python path : /usr/bin/python3
INFO:root:Python version : 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]

INFO:root:or-tools version : 5.1.4041
INFO:root:/home/petrochuk/.local/lib/python3.5/site-packages/py3_ortools-5.1.4041-py3.5-linux-i686.egg/ortools/__init__.py

INFO:root:protobuf version : 3.0.0
INFO:root:/usr/local/lib/python3.5/dist-packages/google/protobuf/__init__.py
```

Error
```
    File "/usr/local/lib/python3.5/dist-packages/ortools/graph/pywrapgraph.py", line 18, in swig_import_helper
      return importlib.import_module(mname)
    File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 986, in _gcd_import
    File "<frozen importlib._bootstrap>", line 969, in _find_and_load
    File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 577, in module_from_spec
    File "<frozen importlib._bootstrap_external>", line 906, in create_module
    File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  ImportError: /usr/local/lib/python3.5/dist-packages/ortools/graph/_pywrapgraph.so: wrong ELF class: ELFCLASS64
```

**Comment by Deepblue129** [comment] 2017-01-27 02:31
On my other issue, it was noted that ortools does not support 32 bit systems. That may be the root cause here. 

But on the other issue, setup.py was able to identify that before I was able to progress this far into the installation.

**Comment by ilo2008** [comment] 2017-02-28 19:45
Hello,

Indeed, 32-bit systems are not supported by or-tools. You are right about what you said : a system check needs to be performed before going further. We will implement it ASAP.

Thank you.

**Comment by Mizux** [comment] 2018-03-12 10:04
Hi,

We won't support 32 bit system so I'll close this issue.

Sorry for the inconvenience.

**Closed by Mizux** 2018-03-12 10:04 UTC
Labels: Python, help wanted
