### ISSUE TITLE
.Net: wrapping AddDimensionDependentDimensionWithVehicleCapacity

### ISSUE THREAD

**Issue by ConnerWestover** [google/or-tools#1273] opened 2019-05-13 13:40 UTC
Hello All,

I'm trying to build the OR-Tools with some modifications to the SWIG interfaces so I can open up the AddDimensionDependentDimensionWithVehicleCapacity for access in C#. I know people have requested this and it's been an issue to get done, but I was hoping to help solve this. I followed the steps here in my initial builds of each branch https://developers.google.com/optimization/install/dotnet/source_windows.

So far I've been able to successfully build the DLLs and Nuget Packages for OR-Tools using the 6.7.x branch, the stable branch, and the 7.1 version release version. I've come into various issues within each version. 

---6.7.x---
I'm able to build the DLLs and I've added them to my solution and they work. Just like before, but regardless of the changes I make to the SWIG interface I can't seem to access the method. I've done as little as just not ignoring the method, and as far as removing all ignores from the wrapper, but I've had no luck. 

---7.1---
I'm able to build the Nuget package and add it to my solution. I can see I have access to that method via intellisense, but when I run the program I get a BadImageException that points to a line where the Google.OrTools.runtime.win-x64.dll is being imported in the SWIG generated code. 

---stable---
Again I'm able to build the nuget packages and add them to my branch like before. I have access to the method (intellisense), but when I run the program I get a BadImageException that now points Google.OrTools.Dll itself. 

For all three, I've tried modifying the csharp/dotnet csproj file in OrTools/dotnet, or OrTools/csharp depending on the version, to remove references to linux and os. I've tried changing how the Google.OrTools.runtime.win-x64dll is found, and lastly I've tried forcing the dlls to compute for a CPU of x64 or x86, neither of which resolved the issue.

Any help would be much appreciated. All I know about SWIG is what I've learned from experimenting with this and I hope that I can help resolve this issue.

**Comment by Mizux** [comment] 2019-05-13 13:50
few things:

1) `v7.1` is a tag and our release/default branch **stable** now point on it.
2) **master** branch is our development branch any PR must be done against it.

3) The problem is not to unignore the method but to correctly *typemap* the arguments.
note: you can see the `.cs` code generated by swig in `ortools/gen/ortools/constraint_solver/RoutingModel.cs` IIRC

**Comment by ConnerWestover** [comment] 2019-05-13 17:06
Thanks for the timely response. 

I think I have the typemapping setup correctly, but after building it I get 'The type initializer for 'Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE' threw an exception.' with an inner exception of 'DllNotFoundException: Unable to load DLL 'Google.OrTools.runtime.win-x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'. 

I have the win-x64 Nuget package added, and it contains that dll. I can't seem to figure where that needs to get adjusted. Any idea?

**Comment by Mizux** [comment] 2019-05-14 08:01
nuget has a local cache for package, we have version number only commit dependent and our makefile may miss few dependencies so sometime *dotnet* cli will use the wrong package (i.e. the previously build and cached).
Try to do a `make clean_dotnet; make dotnet` to regenerate the dotnet part only.

note: you can also try `dotnet nuget locals all --clear` to  only clear the nuget cache (`clean_dotnet` call it BTW)

**Comment by Mizux** [comment] 2019-05-14 12:45
mark it duplicate of #339

**Comment by ConnerWestover** [comment] 2019-05-14 12:57
While I work on this I saw you added this to To do in Kanban 7.2. Does this mean you plan to add/or at least attempt to add this for a 7.2 release this month?

**Comment by ConnerWestover** [comment] 2019-05-15 14:57
When I build Google.OrTools using `make dotnet` it doesn't build the path/file ref/netstandard2.0/Google.OrTools.dll into the package. This happens in a fresh stable pull, before I've made my changes, and after I've made changes. I've tried `make clean_dotnet` and even manually adding the built DLL to the package, but this doesn't compile correctly. Any thoughts?

**Comment by lperron** [comment] 2019-07-19 18:50
No, time dependent dimensions is not mature in C++ and too slow.
We have no immediate plans to export this in other languages.

**Closed by lperron** 2019-07-19 18:50 UTC
Labels: Duplicate, Feature Request, Lang: .NET, Solver: Routing Solver
