### ISSUE TITLE
getting memory leak error in cvrptw_plot.py

### ISSUE THREAD

**Issue by tk120404** [google/or-tools#1134] opened 2019-03-17 11:15 UTC
getting memory leak in 
swig/python detected a memory leak of type 'operations_research::RoutingModel::DisjunctionIndex *', no destructor found.
@Mizux , Please check this

**Comment by tk120404** [comment] 2019-03-17 11:22
@Mizux 
`nodes = [routing.AddDisjunction([manager.NodeToIndex(c)], penalty) for c in non_depot]` is causing memory leak

**Comment by lperron** [comment] 2019-03-17 14:23
Are you building head on master, or a different version.
I thought this was fixed in the latest sources.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 17 mars 2019 à 12:22, Arjunkumar <notifications@github.com> a
écrit :

**Comment by tk120404** [comment] 2019-03-18 07:49
This leak is happening in master branch

**Comment by lperron** [comment] 2019-03-18 09:56
can you print the result of :
make detect_port
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 18 mars 2019 à 08:49, Arjunkumar <notifications@github.com> a
écrit :

**Comment by tk120404** [comment] 2019-03-18 15:01
I hope this helps

```
1
refs:
6004	<class 'list'> ['#-*- coding: utf-8 -*-\n', '# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. M
5742	<class 'list'> ['# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. McGuire\n', '#\n', '# Permiss
2010	<class 'dict'> {4465620648: <weakref at 0x10a401638; to 'type' at 0x10a2bf6a8 (type)>, 4465649184: <weakref at 0x10
1824	<class 'dict'> {'__name__': 'lib', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '_or
1818	<class 'dict'> {'Cryptography_HAS_EC2M': 1, 'Cryptography_HAS_EC_1_0_2': 1, 'Cryptography_HAS_SET_ECDH_AUTO': 1, 'C
1285	<class 'list'> ['os', 'numpy', 'np', 'matplotlib', 'pyplot', 'plt', 'collections', 'namedtuple', 'ortools.constrain
1225	<class 'dict'> {'__module__': 'PyQt5.QtCore', '__weakref__': <attribute '__weakref__' of 'Qt' objects>, '__doc__':
1165	<class 'matplotlib.colors._ColorMapping'> {'xkcd:cloudy blue': '#acc2d9', 'xkcd:dark pastel green': '#56ae57', 'xkcd:dust': '#b2996e', 'xkcd:e
1098	<class 'dict'> {4465503536: <weakref at 0x10a4084f8; to 'type' at 0x10a2a2d30 (bool)>, 140313860550744: <weakref at
1058	<class 'dict'> {'__name__': 'ortools.constraint_solver._pywrapcp', '__doc__': None, '__package__': 'ortools.constra

bytes:
131248	 <_io.BufferedReader name='<stdin>'>
131248	 <_io.BufferedWriter name='<stdout>'>
131248	 <_io.BufferedWriter name='<stderr>'>
73824	 {'__name__': 'lib', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '_or
73824	 {'Cryptography_HAS_EC2M': 1, 'Cryptography_HAS_EC_1_0_2': 1, 'Cryptography_HAS_SET_ECDH_AUTO': 1, 'C
51752	 ['#-*- coding: utf-8 -*-\n', '# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. M
51752	 ['# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. McGuire\n', '#\n', '# Permiss
36984	 {'xkcd:cloudy blue': '#acc2d9', 'xkcd:dark pastel green': '#56ae57', 'xkcd:dust': '#b2996e', 'xkcd:e
36968	 {4465620648: <weakref at 0x10a401638; to 'type' at 0x10a2bf6a8 (type)>, 4465649184: <weakref at 0x10
36968	 {'sys': <module 'sys' (built-in)>, 'builtins': <module 'builtins' (built-in)>, '_frozen_importlib':

types:
16829	 <class 'function'>
8121	 <class 'dict'>
7675	 <class 'tuple'>
5668	 <class 'list'>
5594	 <class 'wrapper_descriptor'>
4571	 <class 'weakref'>
3891	 <class 'builtin_function_or_method'>
3152	 <class 'getset_descriptor'>
2204	 <class 'cell'>
2183	 <class 'type'>

2
refs:
6004	<class 'list'> ['#-*- coding: utf-8 -*-\n', '# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. M
5742	<class 'list'> ['# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. McGuire\n', '#\n', '# Permiss
2010	<class 'dict'> {4465620648: <weakref at 0x10a401638; to 'type' at 0x10a2bf6a8 (type)>, 4465649184: <weakref at 0x10
1824	<class 'dict'> {'__name__': 'lib', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '_or
1818	<class 'dict'> {'Cryptography_HAS_EC2M': 1, 'Cryptography_HAS_EC_1_0_2': 1, 'Cryptography_HAS_SET_ECDH_AUTO': 1, 'C
1285	<class 'list'> ['os', 'numpy', 'np', 'matplotlib', 'pyplot', 'plt', 'collections', 'namedtuple', 'ortools.constrain
1225	<class 'dict'> {'__module__': 'PyQt5.QtCore', '__weakref__': <attribute '__weakref__' of 'Qt' objects>, '__doc__':
1165	<class 'matplotlib.colors._ColorMapping'> {'xkcd:cloudy blue': '#acc2d9', 'xkcd:dark pastel green': '#56ae57', 'xkcd:dust': '#b2996e', 'xkcd:e
1098	<class 'dict'> {4465503536: <weakref at 0x10a4084f8; to 'type' at 0x10a2a2d30 (bool)>, 140313860550744: <weakref at
1058	<class 'dict'> {'__name__': 'ortools.constraint_solver._pywrapcp', '__doc__': None, '__package__': 'ortools.constra

bytes:
131248	 <_io.BufferedReader name='<stdin>'>
131248	 <_io.BufferedWriter name='<stdout>'>
131248	 <_io.BufferedWriter name='<stderr>'>
73824	 {'__name__': 'lib', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '_or
73824	 {'Cryptography_HAS_EC2M': 1, 'Cryptography_HAS_EC_1_0_2': 1, 'Cryptography_HAS_SET_ECDH_AUTO': 1, 'C
51752	 ['#-*- coding: utf-8 -*-\n', '# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. M
51752	 ['# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. McGuire\n', '#\n', '# Permiss
36984	 {'xkcd:cloudy blue': '#acc2d9', 'xkcd:dark pastel green': '#56ae57', 'xkcd:dust': '#b2996e', 'xkcd:e
36968	 {4465620648: <weakref at 0x10a401638; to 'type' at 0x10a2bf6a8 (type)>, 4465649184: <weakref at 0x10
36968	 {'sys': <module 'sys' (built-in)>, 'builtins': <module 'builtins' (built-in)>, '_frozen_importlib':

types:
16829	 <class 'function'>
8121	 <class 'dict'>
7675	 <class 'tuple'>
5668	 <class 'list'>
5594	 <class 'wrapper_descriptor'>
4571	 <class 'weakref'>
3891	 <class 'builtin_function_or_method'>
3152	 <class 'getset_descriptor'>
2204	 <class 'cell'>
2183	 <class 'type'>

3
refs:
6004	<class 'list'> ['#-*- coding: utf-8 -*-\n', '# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. M
5742	<class 'list'> ['# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. McGuire\n', '#\n', '# Permiss
2010	<class 'dict'> {4465620648: <weakref at 0x10a401638; to 'type' at 0x10a2bf6a8 (type)>, 4465649184: <weakref at 0x10
1824	<class 'dict'> {'__name__': 'lib', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '_or
1818	<class 'dict'> {'Cryptography_HAS_EC2M': 1, 'Cryptography_HAS_EC_1_0_2': 1, 'Cryptography_HAS_SET_ECDH_AUTO': 1, 'C
1285	<class 'list'> ['os', 'numpy', 'np', 'matplotlib', 'pyplot', 'plt', 'collections', 'namedtuple', 'ortools.constrain
1225	<class 'dict'> {'__module__': 'PyQt5.QtCore', '__weakref__': <attribute '__weakref__' of 'Qt' objects>, '__doc__':
1165	<class 'matplotlib.colors._ColorMapping'> {'xkcd:cloudy blue': '#acc2d9', 'xkcd:dark pastel green': '#56ae57', 'xkcd:dust': '#b2996e', 'xkcd:e
1098	<class 'dict'> {4465503536: <weakref at 0x10a4084f8; to 'type' at 0x10a2a2d30 (bool)>, 140313860550744: <weakref at
1058	<class 'dict'> {'__name__': 'ortools.constraint_solver._pywrapcp', '__doc__': None, '__package__': 'ortools.constra

bytes:
131248	 <_io.BufferedReader name='<stdin>'>
131248	 <_io.BufferedWriter name='<stdout>'>
131248	 <_io.BufferedWriter name='<stderr>'>
73824	 {'__name__': 'lib', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '_or
73824	 {'Cryptography_HAS_EC2M': 1, 'Cryptography_HAS_EC_1_0_2': 1, 'Cryptography_HAS_SET_ECDH_AUTO': 1, 'C
51752	 ['#-*- coding: utf-8 -*-\n', '# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. M
51752	 ['# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. McGuire\n', '#\n', '# Permiss
36984	 {'xkcd:cloudy blue': '#acc2d9', 'xkcd:dark pastel green': '#56ae57', 'xkcd:dust': '#b2996e', 'xkcd:e
36968	 {4465620648: <weakref at 0x10a401638; to 'type' at 0x10a2bf6a8 (type)>, 4465649184: <weakref at 0x10
36968	 {'sys': <module 'sys' (built-in)>, 'builtins': <module 'builtins' (built-in)>, '_frozen_importlib':

types:
16829	 <class 'function'>
8121	 <class 'dict'>
7675	 <class 'tuple'>
5668	 <class 'list'>
5594	 <class 'wrapper_descriptor'>
4571	 <class 'weakref'>
3891	 <class 'builtin_function_or_method'>
3152	 <class 'getset_descriptor'>
2204	 <class 'cell'>
2183	 <class 'type'>

4
refs:
6004	<class 'list'> ['#-*- coding: utf-8 -*-\n', '# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. M
5742	<class 'list'> ['# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. McGuire\n', '#\n', '# Permiss
2010	<class 'dict'> {4465620648: <weakref at 0x10a401638; to 'type' at 0x10a2bf6a8 (type)>, 4465649184: <weakref at 0x10
1824	<class 'dict'> {'__name__': 'lib', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '_or
1818	<class 'dict'> {'Cryptography_HAS_EC2M': 1, 'Cryptography_HAS_EC_1_0_2': 1, 'Cryptography_HAS_SET_ECDH_AUTO': 1, 'C
1285	<class 'list'> ['os', 'numpy', 'np', 'matplotlib', 'pyplot', 'plt', 'collections', 'namedtuple', 'ortools.constrain
1225	<class 'dict'> {'__module__': 'PyQt5.QtCore', '__weakref__': <attribute '__weakref__' of 'Qt' objects>, '__doc__':
1165	<class 'matplotlib.colors._ColorMapping'> {'xkcd:cloudy blue': '#acc2d9', 'xkcd:dark pastel green': '#56ae57', 'xkcd:dust': '#b2996e', 'xkcd:e
1098	<class 'dict'> {4465503536: <weakref at 0x10a4084f8; to 'type' at 0x10a2a2d30 (bool)>, 140313860550744: <weakref at
1058	<class 'dict'> {'__name__': 'ortools.constraint_solver._pywrapcp', '__doc__': None, '__package__': 'ortools.constra

bytes:
131248	 <_io.BufferedReader name='<stdin>'>
131248	 <_io.BufferedWriter name='<stdout>'>
131248	 <_io.BufferedWriter name='<stderr>'>
73824	 {'__name__': 'lib', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '_or
73824	 {'Cryptography_HAS_EC2M': 1, 'Cryptography_HAS_EC_1_0_2': 1, 'Cryptography_HAS_SET_ECDH_AUTO': 1, 'C
51752	 ['#-*- coding: utf-8 -*-\n', '# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. M
51752	 ['# module pyparsing.py\n', '#\n', '# Copyright (c) 2003-2018  Paul T. McGuire\n', '#\n', '# Permiss
36984	 {'xkcd:cloudy blue': '#acc2d9', 'xkcd:dark pastel green': '#56ae57', 'xkcd:dust': '#b2996e', 'xkcd:e
36968	 {4465620648: <weakref at 0x10a401638; to 'type' at 0x10a2bf6a8 (type)>, 4465649184: <weakref at 0x10
36968	 {'sys': <module 'sys' (built-in)>, 'builtins': <module 'builtins' (built-in)>, '_frozen_importlib':

types:
16829	 <class 'function'>
8121	 <class 'dict'>
7675	 <class 'tuple'>
5668	 <class 'list'>
5594	 <class 'wrapper_descriptor'>
4571	 <class 'weakref'>
3891	 <class 'builtin_function_or_method'>
3152	 <class 'getset_descriptor'>
2204	 <class 'cell'>
2183	 <class 'type'>
```

**Comment by Mizux** [comment] 2019-03-18 15:06
@tk120404 if you are using master, you must have use GNU/Make in order to build the package right, so please give us the return of command `make detect_port`

e.g.
```sh
$: make detect_port                     
Relevant info on the system:
SYSTEM = unix
OS = Linux
PLATFORM = LINUX
PTRLENGTH = 64
PORT = Debian-rodete-64bit
SHELL = /bin/sh
OR_TOOLS_TOP = /usr/local/home/mizux/work/master
OR_TOOLS_VERSION = 7.0.6507
OR_TOOLS_SHORT_VERSION = 7.0
GIT_REVISION = 6507
GIT_HASH = a12526bb6
CMAKE = /usr/local/home/mizux/cmake/bin/cmake
SWIG_BINARY = /usr/bin/swig
SWIG_INC = -I/usr/local/home/mizux/work/master/dependencies/install/include ...
```

**Comment by Mizux** [comment] 2019-03-18 15:10
duplicate of #1030

**Closed by Mizux** 2019-03-18 15:10 UTC
Labels: Bug, Lang: Python, Solver: Routing Solver
