### ISSUE TITLE
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

### ISSUE THREAD

**Issue by bvkeersop** [google/or-tools#925] opened 2018-11-08 11:00 UTC
Hi,

I'm using Google OR.Tools with .NET CORE 2.1. However I'm getting a 
`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'` Error.

I remember getting it before when I didn't set the environment to x64, however it is set to a x64 env.

The error seems to occur when I add a certain amount of of variables to the objective. A few variables doesn't seem to  cause the error, but when I add more it crashes (not at a specific number, sometimes it crashes sometimes it doesn't). But I don' think this is an out of memory exception?

![image](https://user-images.githubusercontent.com/10126707/48194341-0626e780-e34d-11e8-9b79-ecaa5a428a92.png)

![image](https://user-images.githubusercontent.com/10126707/48194358-15a63080-e34d-11e8-8e06-6ca6a1d49aba.png)

Thanks!

**Comment by bvkeersop** [comment] 2018-11-13 15:28
I'm not exactly sure, but I think this issue was caused by re-use of an objective or constraint without reinitialising the solver.

**Comment by bvkeersop** [comment] 2018-12-13 15:11
Hi,
I was using the CBC_MIXED_INTEGER_PROGRAMMING.
I fixed the issue when I last commented, but I'm not sure what exactly went wrong.
Like I said in my previous post I think it had to do with re-using objectives or constraints, but I'm not sure. It was definitly an error on my behalf (since I was able to fix it), but the error message provided was a bit unclear.

**Comment by lperron** [comment] 2019-01-19 19:52
Closing the issue as the problem is resolved.

**Closed by lperron** 2019-01-19 19:52 UTC
Labels: Bug, Lang: .NET, Solver: Linear Solver

**Comment by MrMartinez** [comment] 2019-06-09 23:21
> Closing the issue as the problem is resolved.



> I'm not exactly sure, but I think this issue was caused by re-use of an objective or constraint without reinitialising the solver.

I was calling the code from the txtboxTextChanced. So, i make a new metho y call it from the load.

**Comment by ssharmagithub** [comment] 2019-07-12 09:12
I am facing same issue in my project, i don't know why it's coming but error gone when i re-start the ISS and pool, Do you have any idea what a cause ?

**Comment by ankitkundu23** [comment] 2022-01-27 06:56
> I am facing same issue in my project, i don't know why it's coming but error gone when i re-start the ISS and pool, Do you have any idea what a cause ?

In my case it was not a framework issue rather a SQLite one. I had created 2 indices for the same table (and same set of columns and collation) with different index names. Removing one of the indices resolved the error. Hope this helps!

**Comment by MichalHeller1** [comment] 2023-03-19 15:00
Hi . i have this problem too in my project
and i'm trying to change like to this answer but it doesn't work
maby do you have other answers to this problem?
i have "SQL Server database file"
and the request to the database works good but when i call this from the UI so the problem jumps.
![צילום מסך 2023-03-19 165755](https://user-images.githubusercontent.com/117977589/226184569-91d55a63-ec4c-42c6-8078-8f3217b53af9.png)
