### ISSUE TITLE
callback is never called in SearchForAllSolutions()

### ISSUE THREAD

**Issue by weiyinchiang** [google/or-tools#2058] opened 2020-06-06 08:31 UTC
I am trying to apply the "StopSearch()" function in a callback function to find first a few solutions, with `cp_model.CpSolver()` and its `SearchForAllSolutions()` method. The solver seems to last forever to find the __first__ solution and the callback is never called. Please see the code 1 at the end of this question.

In addition, if I use `solver.SolveWithSolutionCallback()` with exactly the same callback, the first solution is found quickly. However, I cannot find more than one solution by this API. Please see the code 2.

After tracking both the python and C++ code, both functions call [`operations_research::sat::SolveCpModel`](https://github.com/google/or-tools/blob/5ff76b487a6c2006326765d6417964599eedc8c9/ortools/sat/cp_model_solver.cc#L2389). The only difference is that `enumerate_all_solutions=true` for `SearchForAllSolutions()`, while `enumerate_all_solutions=false` for `solver.SolveWithSolutionCallback()`. This makes [this if-clause](https://github.com/google/or-tools/blob/5ff76b487a6c2006326765d6417964599eedc8c9/ortools/sat/cp_model_solver.cc#L2445) false in `SearchForAllSolutions()`, so that `SolvePureSatModel` does not execute before the [`Presolve and expansions`](https://github.com/google/or-tools/blob/5ff76b487a6c2006326765d6417964599eedc8c9/ortools/sat/cp_model_solver.cc#L2481).

I am wondering if this is the reason that my execution of `SearchForAllSolutions()` never returns a single solution. How to solve the problem? Or is there an alternative way to obtain a few solutions without setting `enumerate_all_solutions=true`?

Thanks a lot. And here is my codes to show the above issue.

## Code 1
Python Input:
```python
solver = cp_model.CpSolver()
solution_printer = VarArraySolutionPrinterWithLimit([], 1)
status = solver.SearchForAllSolutions(model, solution_printer)
```
Output:
```
callback initialization begins
callback initialization end
```
__the solver runs for ever and the callback's `on_solution_callback()` is not called.__

=============================
Here is the callback:
```python
class VarArraySolutionPrinterWithLimit(cp_model.CpSolverSolutionCallback):
    
    def __init__(self, schedule, limit):
        print("callback initialization begins")
        cp_model.CpSolverSolutionCallback.__init__(self)
        self.__schedule = schedule
        self.__solution_count = 0
        self.__solution_limit = limit
        print("callback initialization end")

    def on_solution_callback(self):
        print("callback function is called", flush=True)
        self.__solution_count += 1
        print()
        
        if self.__solution_count >= self.__solution_limit:
            print('Stop search after %i solutions' % self.__solution_limit)
            self.StopSearch()

    def solution_count(self):
        return self.__solution_count
```

## Code 2
Python Input:
```python
solver = cp_model.CpSolver()
solution_printer = VarArraySolutionPrinterWithLimit([], 1)
status = solver.SolveWithSolutionCallback(model, solution_printer)
```

Output:
```
callback initialization begins
callback initialization end
callback function is called
```
Stop search after 1 solutions

**Comment by lperron** [comment] 2020-06-06 14:08
Searchforallsolutions is not supported if your model has an objective. Is
it the case ?

Le sam. 6 juin 2020 à 10:31, Wei-Yin Chiang <notifications@github.com> a
écrit :

**Comment by weiyinchiang** [comment] 2020-06-06 15:38
Nope and here is what I did.
```python

def All_Cost():
    num_order = 4
    num_factory = 2
    num_month = 5
    num_material = 5
    scale_y = 10

    all_order = range(num_order)
    all_factory = range(num_factory)
    all_month = range(num_month)
    all_material = range(num_material)

    ncap_jt = np.array([[800, 990, 1180, 1370, 1560],[500, 800, 1100, 1400, 1700]])
    ocap_jt = np.array([[250, 360, 470, 580, 690],[200, 250, 300, 350, 400]])
    
  # Quality Rate
    scale = 100
    u_ij = (np.array([[0.90, 0.88],[0.92, 0.90],[0, 0.89],[0.90, 0.86]])*scale).astype(int)
    v_ij = (np.array([[0.72, 0.73],[0.83, 0.65],[0, 0.84],[0.84, 0.82]])*scale).astype(int)

  #Demanding
    dq = [1000, 3000, 3000, 5400]

  # material limitation
    l_rjt = np.array([[48000, 48000, 48000, 48000, 48000],[40000, 40000, 40000, 40000, 40000],[25000, 25000, 25000, 25000, 25000], [18000, 18000, 18000, 18000, 18000], [27000, 27000, 27000, 27000, 27000]])
  # BOM
    b_ir = np.array([[10, 2, 7, 2, 5],[7, 8, 0, 0, 4],[6, 5, 1, 1, 0],[2, 2, 2, 4, 2]])
  
  #material price
    pp_rt = np.array([[38, 35, 42, 50, 40],[36, 36, 42, 45, 42],[36, 38, 45, 45, 46],[38, 38, 49, 50, 52],[40, 40, 49, 52, 60]])

  #produce price
    scale_pc = 10

    sc_ij = (np.array([[2250, 2750],[2250, 2750],[0, 2750],[2250, 2750]])*scale_pc).astype(int)
    ic_ij = (np.array([[3.1, 3.2],[3.5, 3.6],[0, 3],[3.9, 3.4]])*scale_pc).astype(int)

    pc_ijt = (np.array([[[18, 18, 20, 20, 24],[20, 20, 22, 22, 25]],
            [[24, 24, 24, 24, 30],[35, 35, 35, 35, 50]],
            [[0,0,0,0,0],[28, 28, 28, 28, 56]],
            [[20, 20, 20, 22, 22],[22, 22, 22, 24, 24]]])*scale_pc).astype(int)
    ot_ijt = (np.array([[[21.6, 21.6, 24, 24, 28.8],[24, 24, 26.4, 26.4, 30]],
            [[28.8, 28.8, 28.8, 28.8, 36],[42, 42, 42, 42, 60]],
            [[0,0,0,0,0],[33.6, 33.6, 33.6, 33.6, 67.2]],
            [[24, 24, 24, 26.4, 26.4],[26.4, 26.4, 26.4, 28.8, 28.8]]])*scale_pc).astype(int)
  
    model = cp_model.CpModel()

    schedule = {}
    open_close = {}
    used_jtr = {}
    pq_jtr = {}
    iq_jtr = {}
    price_jtr = {}
    product_price_jti = {}

    for j in all_factory:
        for t in all_month:
            for i in all_order:
                product_price_jti[(j,t,i)] = model.NewIntVar(0,5000000000000,str(i)+'_f_'+str(j)+'_t_'+str(t)+'_1')
                schedule[(i,j,t,0)] = model.NewIntVar(0,2000,str(i)+'_f_'+str(j)+'_t_'+str(t)+'_0')
                schedule[(i,j,t,1)] = model.NewIntVar(0,2000,str(i)+'_f_'+str(j)+'_t_'+str(t)+'_1')
                open_close[(i,j,t)] = model.NewBoolVar(str(i)+'_f_'+str(j)+'_t_'+str(t))

          
                model.Add(schedule[(i,j,t,0)]+ schedule[(i,j,t,1)]>0).OnlyEnforceIf(open_close[(i,j,t)])
                model.Add(schedule[(i,j,t,0)]+ schedule[(i,j,t,1)] ==0).OnlyEnforceIf(open_close[(i,j,t)].Not())

    for j in all_factory:
        for t in all_month:
            model.Add(sum(schedule[(i,j,t,0)] for i in all_order)< ncap_jt[j,t])
            model.Add(sum(schedule[(i,j,t,1)] for i in all_order)< ocap_jt[j,t])
            #model.Add(sum(open_close[(i,j,t)] for i in all_order)<= 1) 
         
    model.Add(sum(open_close[(2,0,t)] for t in all_month) == 0)
    spec_month = [all_month[0:3],all_month[0:4],all_month,all_month]
    
    for i in all_order:
        model.Add(sum(schedule[(i,j,t,0)]*u_ij[i,j]+schedule[(i,j,t,1)]*v_ij[i,j] for j in all_factory for t in spec_month[i]) == dq[i]*scale)

#declare
    Qijt = {}
    for i in all_order:
        for j in all_factory:
            for t in all_month:
                Qijt[(i,j,t)] = model.NewIntVar(0,500000,'Q_f_'+str(j)+'_t_'+str(t))
                model.Add(Qijt[(i,j,t)] == schedule[(i,j,t,0)]+schedule[(i,j,t,1)])

    for j in all_factory: 
        for t in all_month:
            for r in all_material:
                used_jtr[(j,t,r)] = model.NewIntVar(0,500000,'used_f_'+str(j)+'_t_'+str(t)+'_m_'+str(r))
                pq_jtr[(j,t,r)] = model.NewIntVar(0,50000,'pq_f_'+str(j)+'_t_'+str(t)+'_m_'+str(r))
                iq_jtr[(j,t,r)] = model.NewIntVar(0,50000,'iq_f_'+str(j)+'_t_'+str(t)+'_m_'+str(r))
                price_jtr[(j,t,r)] = model.NewIntVar(0,50000000000000,'iq_f_'+str(j)+'_t_'+str(t)+'_m_'+str(r))
        


    for j in all_factory: 
        for t in all_month:
            for i in all_order:
                is_ijt = (schedule[(i,j,t,0)]*u_ij[i,j]+schedule[(i,j,t,1)]*v_ij[i,j]) + 2* sum(schedule[(i,j,tt,0)]*u_ij[i,j]+schedule[(i,j,tt,1)]*v_ij[i,j] for tt in range(t))  #200
                storage_fee = ic_ij[i,j] * is_ijt  #2000x
                seting_fee = sc_ij[i,j]*open_close[i,j,t] #10x
                people_fee = schedule[(i,j,t,0)]*pc_ijt[i,j,t] + schedule[(i,j,t,1)]*ot_ijt[i,j,t] #10x
                model.Add(product_price_jti[(j,t,i)] == people_fee*200 + seting_fee*200 + storage_fee )  #2000x
                  
            for r in all_material:
                model.Add(used_jtr[(j,t,r)] == sum(Qijt[(i,j,t)] * b_ir[i,r] for i in all_order))
                model.Add(pq_jtr[(j,t,r)] <= l_rjt[r,t])
                model.Add(price_jtr[(j,t,r)] == 200*pp_rt[r,t] * (pq_jtr[(j,t,r)]*scale_y)) #2000x


    for j in all_factory:
        for r in all_material:
            model.Add(pq_jtr[(j,0,r)] - used_jtr[(j,0,r)] == iq_jtr[(j,0,r)])
            for t in all_month[1:]:
                model.Add(pq_jtr[(j,t,r)] + iq_jtr[(j,t-1,r)]-used_jtr[(j,t,r)] == iq_jtr[(j,t,r)])

    obj_var = model.NewIntVar(0,5000000000000,'material_cost')
    Total = sum(price_jtr[(j,t,r)]for r in all_material for t in all_month for j in all_factory)
    Total += sum(product_price_jti[(j,t,i)] for j in all_factory for t in all_month for i in all_order)

    model.Add(obj_var == Total)
    #model.Minimize(obj_var)
  

    print('solving......................')
  #===================================================================
    solver = cp_model.CpSolver()
      
    solution_printer = VarArraySolutionPrinterWithLimit([], 1)
    #status = solver.SearchForAllSolutions(model, solution_printer)
    status = solver.SolveWithSolutionCallback(model, solution_printer)

    
```

**Comment by lperron** [comment] 2020-06-07 12:58
from what I see, we perform aggressive presolve if we know you are not searching for all solutions.
With them, finding a solution is easy. Without them, it seems to be quite hard.

**Comment by lperron** [comment] 2020-06-12 16:31
Closing the issue. The solution will be found, eventually. It is just that the problem is much harder to solve.

**Closed by lperron** 2020-06-12 16:31 UTC
Labels: Help Needed, Lang: Python, Solver: CP / CP-SAT Solver
